### ISSUE TITLE
Feature request: Get error message

### ISSUE THREAD

**Issue by GaidamakUA** [2shady4u/godot-sqlite#1]
I'm working on SQLite game and it wold be nice to be able to access SQL error message.

**Comment by 2shady4u** [comment]
Hello @GaidamakUA !

I could add a binding to the error message if that would interest you:
https://www.sqlite.org/c3ref/errcode.html

Could you please explain in a little more detail:
- Your use case
- The extent to which you want access to this error? (do you want the extended error code as well?)

Greetings!

**Comment by GaidamakUA** [comment]
@2shady4u Thanks for reply. This is my game: https://gaidamakua.itch.io/sqlitedetective.
Now, when user does something wrong - I show only "SQL Error" in output. I want output to be more meaningful. I think, string that's printed in console would be enough.

**Comment by 2shady4u** [comment]
Okay, I'm working on it!
(Give me a few days)

**Comment by 2shady4u** [comment]
Okay, the latest release now implements this feature.
Could you test it out? It should work without any issue.

**Comment by GaidamakUA** [comment]
Work like a charm.
