### ISSUE TITLE
Question - c#

### ISSUE THREAD

**Issue by zbyna** [2shady4u/godot-sqlite#103]
May be clear from the nature of this project ( GDNative), but I am beginner so let me please to ask :slightly_smiling_face:  .
Does this plugin work with c# in Godot mono version ?
Thanks.

**Comment by 2shady4u** [comment]
Hi @zbyna,

It is possible to use this plugin in Godot mono, but it's imo not a good idea.

Instead, I would recommend that you use the SQLite functionalities that are natively available in C# (https://zetcode.com/csharp/sqlite/).

**Comment by zbyna** [comment]
Thanks for tips!  I will try both ways and choose one with less Android and HTML5 export problems.  I thought that gdnative plugin would generace less problems during export to various platform but it seems as bad assumption 🙂
