### ISSUE TITLE
hi, how could i avoid my export generate db?

### ISSUE THREAD

**Issue by sesenta** [2shady4u/godot-sqlite#11]
when i export i must replace auto-generate db with my db, is possible avoid executable generate a new db?

thanks

**Comment by 2shady4u** [comment]
Hello!

I'm unsure what you are actually asking? 🙈 If I understand it correctly:
1. You export your game
2. You run your game and it creates a new db?
3. You have to copy-paste your own db?

Please clarify 🤣

**Comment by sesenta** [comment]
hahaha thanks so much for your answers, and yes your 3 points are correct and sorry my english xD.

i'm not creating the db by code instead i'm using **DB browser for sqlite**, Then if is possible when i run my game don't create a new empty Database will be great.

Is nothing in code creating DB but in assets is a DB copy filled, but when i export that database is empty, then i need replace it manually anyway.

I'm tried Project > Export > Resources > filters to exclude > .db

**Comment by 2shady4u** [comment]
mmmh

Normally when the plugin already finds an existing DB it won't overwrite it with an empty one.
In your case, does the plugin overwrite yours?

Apologies, I'm still a bit confused what is actually happening 🤔

**Comment by sesenta** [comment]
[https://youtu.be/Z03TwOPw__A](url) i made this little video XD

**Comment by 2shady4u** [comment]
Thanks for the video 😄 

So what you can do is the following:
- Add the  'users.db' to the "Filters to export non-resource files" field in the export settings. This should make Godot copy your database to the build folder as well.

**Comment by sesenta** [comment]
thanks you, solution above don't work :C [https://youtu.be/R4gtuB2Af4M](https://youtu.be/R4gtuB2Af4M)

**but this is not really a problem, only a little bit annoying .**

before close the issue can you answer to me this: 

i'm making a mmo game, so i need in the future set server with godot headless or godot server, it works perfectly in normal projects; but has errors if project use gdnative, the solution is maybe simple:
[how-to-open-gdnative-projects-with-headless-server-godot](https://godotengine.org/qa/63890/how-to-open-gdnative-projects-with-headless-server-godot?show=63890#q63890)

_solution:
You have to manually add entry/dependencies to the *.gdnlib file. If you are compiling for linux, for instance, copy the lines with the paths to your library and dependencies but use Server instead of X11.64:_

[entry]

**X11.64="res://path/to/my/lib.so"**

**Server="res://path/to/my/lib.so"**

where can i edit that? (maybe need i download this project and edit?) thanks

**Comment by 2shady4u** [comment]
Hey :)

You'll need to add a wildcard * to the export-field, like this:
![Capture](https://user-images.githubusercontent.com/42484461/82467728-46c6fb80-9ac2-11ea-9373-0e94acaf1f50.PNG)
Otherwise it won't find your users.db

**Regarding the headless and server versions**, you'll have to add those entries to the gdsqlite.gdnlib:
https://github.com/2shady4u/godot-sqlite/blob/master/demo/addons/godot-sqlite/bin/gdsqlite.gdnlib
(You have this file if you downloaded the plugin from the asset library)

Just change the file to this:
```
[general]

singleton=false
load_once=true
symbol_prefix="godot_"
reloadable=false

[entry]

X11.64="res://addons/godot-sqlite/bin/x11/libgdsqlite.so"
Server="res://addons/godot-sqlite/bin/x11/libgdsqlite.so"
Windows.64="res://addons/godot-sqlite/bin/win64/libgdsqlite.dll"
OSX.64="res://addons/godot-sqlite/bin/osx/libgdsqlite.dylib"

[dependencies]
X11.64=[  ]
Server=[  ]
Windows.64=[  ]
OSX.64=[  ]
```
(IMPORTANT: I never tested this! But I see no reason why it wouldn't work)

**Comment by sesenta** [comment]
**Server and Headless work perfectly, i'm so happy <3, could you add that same lines in github maybe for anyone  who also needs it?**

but *.db don't work xD

is weird than i execute the game and  the empty database is generate. because my code is only like this:

```
var db

func _ready():
	db = SQLite.new()
	db.path = "res://users"
	db.open_db()
```
and
```
func _search():
        db.query("SELECT * FROM " + 'users' +  ";") 
```
but is not a problem, i can replace the db or even having a copy db in the folder where my executable is generated and works perfectly (is not replace when execute the game)

**Comment by 2shady4u** [comment]
Hello! I see you closed this :)
I do have one more question though:
Could you just show me the statement necessary for the Headless build?
Is it just this?

```
[general]

singleton=false
load_once=true
symbol_prefix="godot_"
reloadable=false

[entry]

X11.64="res://addons/godot-sqlite/bin/x11/libgdsqlite.so"
Server="res://addons/godot-sqlite/bin/x11/libgdsqlite.so"
Headless="res://addons/godot-sqlite/bin/x11/libgdsqlite.so"
Windows.64="res://addons/godot-sqlite/bin/win64/libgdsqlite.dll"
OSX.64="res://addons/godot-sqlite/bin/osx/libgdsqlite.dylib"

[dependencies]
X11.64=[  ]
Server=[  ]
Headless=[  ]
Windows.64=[  ]
OSX.64=[  ]
```

So I can add this in a future release :)
