### ISSUE TITLE
About binary file size (two wasm file comparison)

### ISSUE THREAD

**Issue by douyw** [2shady4u/godot-sqlite#110]
The wasm file in the demo is located at `demo\addons\godot-sqlite\bin\javascript\libgdsqlite.wasm`, 3536KB in size.

The `sqlite3.wasm` file used [here](https://sqlite.org/wasm/doc/tip/demo-123.html) only has 779.89 KB. ([the wasm file](https://sqlite.org/wasm/doc/tip/jswasm/sqlite3.wasm))

The wrapper size = 3536KB - 779.89 KB = 2756KB. So large?

**Comment by 2shady4u** [comment]
Hello @douyw 

The wrapper size is indeed quite large at the moment.
It might be worth investigating the compilation flags for the javascript compilation at some point.

**Comment by 2shady4u** [comment]
Closing this issue as the entire buildsystem for the web compilation is now directly inherited from [godot-cpp](https://github.com/godotengine/godot-cpp).
Any modification of the compilation flags needs to be done on their side.
