### ISSUE TITLE
For Godot 4, is there any chance for a release version or adding this plugin to the Godot asset store?

### ISSUE THREAD

**Issue by hyaterreka** [2shady4u/godot-sqlite#119]
I noticed that the Godot 4 version of the plugin does not have any releases and it isn't in the asset store either. When do you think either one of the options will be available? Thank you!

**Comment by Dfred** [comment]
for compiled versions, you can find GitHub Actions that build artifacts. 
That's what @2shady4u did [there](https://github.com/2shady4u/godot-sqlite/actions/workflows/build.yml)

**Comment by hyaterreka** [comment]
Thank you!
