### ISSUE TITLE
SQL errors when I change anything in the module and recompile

### ISSUE THREAD

**Issue by radishes** [2shady4u/godot-sqlite#12]
Hi, thank you for writing this plugin. I've been having fun with it.

When I use the official release of the plugin from the Asset store, it works fine. When I pull down the master branch and build master myself, and copy `demo/addons/godot-sqlite` from the build into my project, the plugin works fine.

But when I make any code changes and compile, and try to use my compiled plugin, I frequently get lots of weird errors. And I see bad data coming back from the database. My app crashes, probably from the weird data that's being returned. Here are some examples of errors I commonly see -- it's different every time I run my app:

```
 --> SQL error: unrecognized token: ""
 --> SQL error: near "D": syntax error
 --> SQL error: near "N": syntax error
 --> SQL error: unrecognized token: ""
 --> SQL error: near "R": syntax error
 --> SQL error: near "c": syntax error
 --> SQL error: near "/": syntax error
Unicode error: invalid utf8
 --> SQL error: near "e_callback
Closed database (
```

The changes I'm testing are really small. Like wrapping an existing print statement in an if block.

Some things I've tried:

- Cleaning my build with `scons -c` and re-building
- Building the plugin and godot-cpp with both debug and release
- Running latest Godot stable v3.2.1 and latest beta v3.2.2

scons output:

```
E:\src\godot-sqlite>scons p=windows target=release
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cl /Fosrc\gdsqlite.obj /c src\gdsqlite.cpp /TP /nologo -DWIN32 -D_WIN32 -D_WINDOWS -W3 -GR -D_CRT_SECURE_NO_WARNINGS -O2 -EHsc -DNDEBUG -MD /I. /Igodot-cpp\godot_headers /Igodot-cpp\include /Igodot-cpp\include\core /Igodot-cpp\include\gen /Isrc
gdsqlite.cpp
E:\src\godot-sqlite\godot-cpp\include\core\Vector2.hpp(218): warning C4244: 'argument': conversion from 'double' to 'real_t', possible loss of data
E:\src\godot-sqlite\godot-cpp\include\core\Vector2.hpp(217): warning C4244: 'argument': conversion from 'double' to 'real_t', possible loss of data
cl /Fosrc\library.obj /c src\library.cpp /TP /nologo -DWIN32 -D_WIN32 -D_WINDOWS -W3 -GR -D_CRT_SECURE_NO_WARNINGS -O2 -EHsc -DNDEBUG -MD /I. /Igodot-cpp\godot_headers /Igodot-cpp\include /Igodot-cpp\include\core /Igodot-cpp\include\gen /Isrc
library.cpp
E:\src\godot-sqlite\godot-cpp\include\core\Vector2.hpp(218): warning C4244: 'argument': conversion from 'double' to 'real_t', possible loss of data
E:\src\godot-sqlite\godot-cpp\include\core\Vector2.hpp(217): warning C4244: 'argument': conversion from 'double' to 'real_t', possible loss of data
cl /Fosrc\sqlite\sqlite3.obj /c src\sqlite\sqlite3.c /nologo -DWIN32 -D_WIN32 -D_WINDOWS -W3 -GR -D_CRT_SECURE_NO_WARNINGS -O2 -EHsc -DNDEBUG -MD /I. /Igodot-cpp\godot_headers /Igodot-cpp\include /Igodot-cpp\include\core /Igodot-cpp\include\gen /Isrc
sqlite3.c
link /nologo /dll /out:demo\addons\godot-sqlite\bin\win64\libgdsqlite.dll /implib:demo\addons\godot-sqlite\bin\win64\libgdsqlite.lib /LIBPATH:godot-cpp\bin libgodot-cpp.windows.release.64.lib src\gdsqlite.obj src\library.obj src\sqlite\sqlite3.obj
   Creating library demo\addons\godot-sqlite\bin\win64\libgdsqlite.lib and object demo\addons\godot-sqlite\bin\win64\libgdsqlite.exp
scons: done building targets.
```

Is there something I'm missing?

**Comment by 2shady4u** [comment]
hello, I see that you are compiling this on Windows right? What version of Visual Studio are you using? Those warnings about conversions between double and real_t cam be ignored (they are godot-cpp related, nothing i can do about them. Is your database using utf8?

**Comment by radishes** [comment]
That's right, this is on Windows. I'm using Visual Studio 2019 Professional. My database was created by the plugin itself. There shouldn't be any utf-8 encoded values in it. I'm also setting these: `PRAGMA synchronous=1; PRAGMA journal_mode=WAL;` but in my testing I have the same issues with or without these PRAGMAs.

**Comment by radishes** [comment]
[repro-sqlite.zip](https://github.com/2shady4u/godot-sqlite/files/4642327/repro-sqlite.zip)

I have created a repro that demonstrates what I'm seeing. Inserting always works fine, but the repro usually crashes while selecting rows -- but only when selecting more than one row at a time. Replacing my `addons/godot-sqlite` with the official one fixes the problem. The only changes in my build are here: https://github.com/radishes/godot-sqlite/commit/e73fdc78916c78164bc09fd7555aaed0930a4df2

It usually crashes without any errors that I can see, but while testing it, I did get this interesting error once that actually points to something in Godot:

```
ERROR: encode_variant: Method failed. Returning: ERR_BUG
   At: core/io/marshalls.cpp:1384
ERROR: _put_variable: Failed to encode variant.
   At: scene/debugger/script_debugger_remote.cpp:116
ERROR: encode_variant: Method failed. Returning: ERR_BUG
   At: core/io/marshalls.cpp:1384
ERROR: decode_variant: Condition "(type & 0xFF) >= Variant::VARIANT_MAX" is true. Returned: ERR_INVALID_DATA
   At: core/io/marshalls.cpp:112
ERROR: Error when trying to decode Variant.
   At: core/io/marshalls.cpp:525
ERROR: _notification: Condition "ret != OK" is true.
   At: editor/script_editor_debugger.cpp:1416
```

**Comment by 2shady4u** [comment]
Hello! I do think it has something to do with discrepancies between Visual Studio versions.
For reference, I'm using VS2017 Community to compile the plugin.

I downloaded your repro-sqlite.zip and ran the `database.gd` file in the demo-project but didn't see any errors? Does the `database.gd`-file run in your case? If yes, could you give me a GDScript script that throws these errors? I'll need something to be able to reproduce these errors.

**Also**: Are you using English as your database language? Or are you using some symbols that aren't in the English alphabet? Like Arabic, Cyrillic, Greek ? Or upside down question marks ¿ or interrobangs?

I recompiled your code (on your fork) with VS2019 Community just for reference and it seems to work perfectly; Here's the compiled DLL:

**Comment by radishes** [comment]
Thank you for taking a look at this. I tried VS2017 Community and got the same result. My database has only English language ASCII characters in it. I ran my repro project with the VS2019 compiled version you uploaded and it still crashes.

The repro project I uploaded has a `Start.tscn` that reproduces the problem for me. In this repro, it usually doesn't throw errors, but it does crash the game. The repro project inserts 10000 rows into the database, and then selects them back out in groups of 100. If this succeeds, the last thing printed should be "Done selecting". What actually happens most of the time is that the project crashes at some point during a select of multiple rows from the database. Here's an example output of a test run I did which crashed while selecting rows 300-400.

```
Initializing the database
Inserting 10000 rows
Done inserting
About to select some rows...
Selected 100 rows
About to select some rows...
Selected 200 rows
About to select some rows...
Selected 300 rows
About to select some rows...
```

The program crashed at that point and exited. Here's another time when it showed the syntax errors:

```
Initializing the database
Inserting 10000 rows
Done inserting
About to select some rows...
Selected 200 rows
About to select some rows...
 --> SQL error: near "n": syntax error
Selected 400 rows
About to select some rows...
 --> SQL error: unrecognized token: "{"
```

**Comment by 2shady4u** [comment]
Heyo, I don't know **why** this exactly happens...

But I do know **how** you can fix it:
Change your condition from:
`var condition = "'number >= {0}' AND 'number < {0} + {1}'".format([i, step])`
to:
`var condition = "'number >= {0}' AND 'number < {0} + {1}'".format([i, step])`

As discussed here:
https://stackoverflow.com/questions/19323922/sqlite-unrecognized-token-exception-in-insert/19324035

Test it out and tell me if it works.
Afterwards we can see what can be changed in the source code.
