### ISSUE TITLE
Need rebuild for Godot beta 14 ?

### ISSUE THREAD

**Issue by git2013vb** [2shady4u/godot-sqlite#124]
**Environment:**
Debian 11
v4.0.beta14.official [28a24639c]

**Issue description:**
![image](https://user-images.githubusercontent.com/13235119/213993426-c04f5b39-f4ac-4887-9ad2-6e7804b5269a.png)

**Steps to reproduce:**
na

**Minimal reproduction project:**
na

**Additional context**
na

**Comment by 2shady4u** [comment]
Hi @git2013vb,

This should now be fixed in #125
You can download the new binaries in the Github Actions tab:
https://github.com/2shady4u/godot-sqlite/actions

**Comment by git2013vb** [comment]
Thanks :)
