### ISSUE TITLE
error reading timestamps with milliseconds

### ISSUE THREAD

**Issue by gabriel-del-nardo** [2shady4u/godot-sqlite#13]
when a timestamp is saved like 1592258339000 as an integer and then consulted the resulting variable in godot looks something like -1174527816 as if it was wrapping around the number.

- when consulted using db browser it behaves as expected.

- works fine if you use only seconds.

- writing the timestamp directly into a variable or consulting from an api works fine with the milliseconds format.

**Comment by 2shady4u** [comment]
Hello @gabriel-del-nardo 

I thought I already fixed this issue a loooong time ago 🤔 
But it seems not?

So when I go through my code I see that I did the following:
`column_value = Variant((int)sqlite3_column_int64(stmt, i));`

which seems correct at the time but maybe I'm doing something wrong here 🤔 

So the number you get corresponds to the one you would get if you did following calculation:
`1592258339000  - (2**32)*742 = -1174527816`

Where 2147483647 is the 32-bit integer maximum, so it definitely seems like some kind of overflow here 🤔 

Could you give me a minimal reproduction example?

**Comment by gabriel-del-nardo** [comment]
[timestamp test.zip](https://github.com/2shady4u/godot-sqlite/files/4786686/timestamp.test.zip)
here, just add the addon and run

**Comment by 2shady4u** [comment]
@gabriel-del-nardo  Just tested it and indeed I get the same bug.
Checking out solutions now...

**Comment by 2shady4u** [comment]
Okay I fixed it by change the (int) to an (int64_t) cast

`column_value = Variant((int)sqlite3_column_int64(stmt, i));`

to:

`column_value = Variant((int64_t)sqlite3_column_int64(stmt, i));`

If I may ask: **What platform are you on?** Cause I won't be able to compile for mac immediately, but could immediately give you the DLL is you are using windows.

**Comment by gabriel-del-nardo** [comment]
i'm on linux but i's ok, ill change the line and recompile

**Comment by 2shady4u** [comment]
okay! :D Tell me if it doesn't work!
