### ISSUE TITLE
Report to console when open_db() is opened twice

### ISSUE THREAD

**Issue by Cryptoclysm** [2shady4u/godot-sqlite#139]
**Is your feature request related to a problem? Please describe.**
For the past few days I have been trying to track down a memory leak in my Godot server. Eventually, I found an open_db() without an accompanying close_db(). This was causing a leak of around 1MB every 10 seconds or so in my code, since the call happened fairly frequently.

**Describe the solution you'd like**
When calling open_db() on an instance of gdsqlite where the db is already open, gdsqlite should:
1. Throw an error/warning to the console
2. Ignore the open_db command, since there is no reason that I know of to open_db() on an open database.

**Describe alternatives you've considered**
Step 2 could be omitted, but that would open up the possibility of the developer leaking memory.

**Additional context**
I am running a godot server on a Linux machine. There is complex SQLite usage over multiple DBs, and so I'm very conscious of avoiding errors and memory issues that may cause the server to misbehave long-term, which is how I caught [issue 88](https://github.com/2shady4u/godot-sqlite/issues/88).
Thanks!

**Comment by 2shady4u** [comment]
This request has now been implemented in f6e571eb9c6eb12193cccb1633ee09cf2ab9a306

**Comment by 2shady4u** [comment]
This request is now part of the latest [release](https://github.com/2shady4u/godot-sqlite/releases/tag/v4.3)!
