### ISSUE TITLE
create_table() crashes running App when, default is set incorrectly

### ISSUE THREAD

**Issue by zurrealStudios** [2shady4u/godot-sqlite#142]
Hopefully this wasn't already reported, could not find a report with the same Issue. If yes then I am sorry

**Environment:**
 - OS: Linux Distribution: Manjaro 22.1.0 / Kernel 6.1.25-1
 - Godot version: 4.0.2
 - _godot-sqlite_ version: 4.0

**Issue description:**
When creating a table with the `create_table()` function and the default value is NOT set in quotation marks, the program will just crash, without any error message. It would be nice, if there would be an error message telling what went wrong.

**Steps to reproduce:**
Create a dictionary variable with badly set default value (see below)
Create table with `create_table()`

**Minimal reproduction project:**
```
@onready var SQL: SQLite = SQLite.new()
var table: Dictionary

func _ready():
    table["id"] = { "data_type" : "int", "primary_key" : true, "auto_increment" : true }
    table["data"] = { "data_type" : "int", "default" : -1 } # <-- this should be "-1"

    SQL.create_table("test_table", table)
```

Thank you for your great Addon and keep up the great work :D!

**Comment by 2shady4u** [comment]
![image](https://github.com/2shady4u/godot-sqlite/assets/42484461/f739eba8-e391-40aa-9b27-cc5313100f5a)

Hello @zurrealStudios
I've added some additional schema validation to the create_table()-method that should give the user some error message.
It's implemented in 792189a and will be part of the next SQLite for Godot 4.X+ release.

**Comment by zurrealStudios** [comment]
Awesome, thank you very much :)
Also big thanks for this awesome Addon and keep on keepin' on :D!

**Comment by 2shady4u** [comment]
I have fixed some issues with the table validation in the latest [release](https://github.com/2shady4u/godot-sqlite/releases/tag/v4.3). Closing this issue because the original issue has been solved.
