### ISSUE TITLE
Local compiling fails on Windows

### ISSUE THREAD

**Issue by jospic** [2shady4u/godot-sqlite#143]
**Environment:**
 - OS: Windows 
 - Godot version: 4
 - _godot-sqlite_ version:  release 24

**Issue description:**
I'm trying to compile the extension for Godot 4 locally on Windows 10, to make some customizations.
I followed the build instructions but it seems that some dependencies are missing.
How can I fix? Thanks in advance.

`fatal error: gdnative_api_struct.gen.h: No such file or directory
`
**Steps to reproduce:**
scons platform=windows

**Minimal reproduction project:**

**Additional context**

**Comment by 2shady4u** [comment]
Hello @jospic 

- Did you correctly update the godot-cpp submodule? (git submodule update --init)
- What is the compiler that you are using?

**Comment by jospic** [comment]
Hi,
usually for Windows i use cross compiling on linux bash (Ubuntu 20.04 for Windows), using mingw64.
Thnks in advance.
-j

**Comment by 2shady4u** [comment]
> Hi, usually for Windows i use cross compiling on linux bash (Ubuntu 20.04 for Windows), using mingw64. Thnks in advance. -j

Hello :) 
I have never tried cross-compiling the Windows binaries on Linux **for Godot 4.0**
There's probably some upgrades that have to be done to the SConstruct file.

**Comment by cridenour** [comment]
> > Hi, usually for Windows i use cross compiling on linux bash (Ubuntu 20.04 for Windows), using mingw64. Thnks in advance. -j
> 
> Hello :) I have never tried cross-compiling the Windows binaries on Linux **for Godot 4.0** There's probably some upgrades that have to be done to the SConstruct file.

It works! I've been doing it all along. It by defaults creates a static library and a smaller one at that.

**Comment by 2shady4u** [comment]
Compilation with MinGW now seems to be correctly supported and the binary obtained using MinGW is now the default binary included in the releases for Windows.
