### ISSUE TITLE
Extension doesn't load since 4.1 beta 2

### ISSUE THREAD

**Issue by koenheltzel** [2shady4u/godot-sqlite#148]
**Environment:**
 - OS: Windows
 - Godot version: 4.1 beta 2 & beta 3
 - _godot-sqlite_ version: 4.1 release (latest at this time)

**Issue description:**

**Steps to reproduce:**
Open & run the godot-sqlite demo project in Godot 4.1 beta 2 or 3

Output when opening the demo project:
```
  core/extension/gdextension.cpp:593 - GDExtension configuration file must contain a "configuration/compatibility_minimum" key: res://addons/godot-sqlite/gdsqlite.gdextension
  Failed loading resource: res://addons/godot-sqlite/gdsqlite.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
  editor/editor_data.cpp:880 - Index p_idx = -1 is out of bounds (edited_scene.size() = 1).
  editor/editor_data.cpp:683 - Index p_idx = -1 is out of bounds (edited_scene.size() = 1).
  editor/editor_data.cpp:745 - Index p_idx = -1 is out of bounds (edited_scene.size() = 1).
  res://database.gd:3 - Parse Error: Could not find type "SQLite" in the current scope.
  res://database.gd:5 - Parse Error: Identifier "SQLite" not declared in the current scope.
  res://database.gd:5 - Parse Error: Assigned value for constant "verbosity_level" isn't a constant expression.
  res://database.gd:55 - Parse Error: Identifier "SQLite" not declared in the current scope.
  res://database.gd:159 - Parse Error: Identifier "SQLite" not declared in the current scope.
  res://database.gd:227 - Parse Error: Identifier "SQLite" not declared in the current scope.
  res://database.gd:276 - Parse Error: Identifier "SQLite" not declared in the current scope.
  res://database.gd:331 - Parse Error: Identifier "SQLite" not declared in the current scope.
  res://database.gd:370 - Parse Error: Identifier "SQLite" not declared in the current scope.
  res://database.gd:390 - Parse Error: Identifier "SQLite" not declared in the current scope.
```
Error popup when running the demo project:
![2023-06-22 10_24_10-Main tscn - SQLite Demo - Godot Engine](https://github.com/2shady4u/godot-sqlite/assets/246064/9da182e0-fe09-4f04-82b1-d958793f84c8)

**Comment by thearduinoguy** [comment]
I have the same issue using 4.1 Beta 3

**Comment by 2shady4u** [comment]
Hello @thearduinoguy and @koenheltzel 

There's no release of godot-cpp yet for Godot 4.1 so I can't compile godot-sqlite for that version yet...

**Comment by thearduinoguy** [comment]
FYI it works with Godot 4.1 Beta 1 but not later versions.

**Comment by go-stuff** [comment]
Good morning, just looked at the godot-cpp repo and it has a warning that the master branch is for 4.1

Warning
This repository's master branch is only usable with the latest version of Godot's ([GDExtension](https://godotengine.org/article/introducing-gd-extensions)) API (Godot 4.1 and later).

**Comment by thearduinoguy** [comment]
Thanks. So this will work with today's Godot release?

**Comment by JonnyTech** [comment]
+1 from me, 4.1 fixes some bugs that I encountered so would love to see a build targetting it

**Comment by git2013vb** [comment]
It will ask to add this row under [configuration]
`compatibility_minimum = 4.1.0 `

But if I follow the source code in demo folder and I set instead `compatibility_minimum = 4.1` godot will crash

Still, after setting the correct key I still have the error:

` core/extension/gdextension.cpp:628 - No GDExtension library found for current OS and architecture (linux.x86_64) in configuration file: res://addons/godot-sqlite/gdsqlite.gdextension`

**Comment by artcattleya** [comment]
I have error (core/extension/gdextension.cpp:593) too with 4.1 Godot

**Comment by 2shady4u** [comment]
A new release has been made for Godot v4.1 and can be found here:
https://github.com/2shady4u/godot-sqlite/releases/tag/v4.2

If there's any new issues with this release, please open a new issue 😄

**Comment by JonnyTech** [comment]
Yes it is...

![image](https://github.com/2shady4u/godot-sqlite/assets/3584732/8c74be60-97bb-49c0-9008-77792bf2d086)
