### ISSUE TITLE
select_rows returns by instance on gd-extension branch

### ISSUE THREAD

**Issue by filkata** [2shady4u/godot-sqlite#153]
I am trying to use the extension on 4.1 and select_rows seems to return by reference rather than by value, is this a case of just needing to apply the change from commit 7110d30 over to the gd-extension branch?

**Comment by filkata** [comment]
I have opened https://github.com/2shady4u/godot-sqlite/pull/154

**Comment by filkata** [comment]
Why did some platforms in https://github.com/2shady4u/godot-sqlite/actions/runs/6004027462 failed to build? I wanted to take the Windows dll files from there.

**Comment by 2shady4u** [comment]
> Why did some platforms in https://github.com/2shady4u/godot-sqlite/actions/runs/6004027462 failed to build? I wanted to take the Windows dll files from there.

It seems like either the Github runners or the Python package server had a small hiccup.
I have restarted the failed jobs and now everything went fine 😄 

Closed in #154
