### ISSUE TITLE
Parser Error: Class "godot-sqlite.gd" cannot be constructed as it is based on abstract native class "EditorPlugin".

### ISSUE THREAD

**Issue by doanhmdp** [2shady4u/godot-sqlite#157]
I'm using GD4.1.1 and got this error after installing godot-sqlite.
Please help me fix it.
It would be great if there were video tutorials from the plugin developer himself
![gd error](https://github.com/2shady4u/godot-sqlite/assets/68715139/0e7d71da-8cf0-4026-b87f-71f939851089)

**Comment by 2shady4u** [comment]
Hello @doanhmdp,

I will investigate asap.

**Comment by doanhmdp** [comment]
Oh, so glad you answered me.
Luckily I read your [document ](https://github.com/2shady4u/godot-sqlite/issues/71)and I was able to resolve this error
I want to leave this comment for those who come later if there is an error
After installing the plugin, for the 4x version, there is no need to declare "Const...path..", we can use sql functions (for example: db = SQLite.new())

**Comment by doanhmdp** [comment]
> Xin chào@doanhmdp,
> 
> Tôi sẽ điều tra càng sớm càng tốt.

Oh, so glad you answered me.
Luckily I read your [document ](https://github.com/2shady4u/godot-sqlite/issues/71)and I was able to resolve this error
I want to leave this comment for those who come later if there is an error
After installing the plugin, for the 4x version, there is no need to declare "Const...path..", we can use sql functions (for example: db = SQLite.new())

It's great that it works correctly, can I ask how to call only the number instead of calling the column name as well?
![gd error](https://github.com/2shady4u/godot-sqlite/assets/68715139/50044965-3372-4b0b-8849-6b503f7c7ce8)

**Comment by 2shady4u** [comment]
I am glad you got it to work!
Closing this issue as it has been solved! 😄
