### ISSUE TITLE
Parser Error: Could not find type "SQLite" in the current scope.

### ISSUE THREAD

**Issue by shackra** [2shady4u/godot-sqlite#159]
**Environment:**
 - OS: NixOS 23.11
 - Godot version: v4.2.stable.nixpkgs [46dc27791]
 - _godot-sqlite_ version: 4.2?

**Issue description:**
Unable to start my project because of "Parser Error: Could not find type "SQLite" in the current scope."

![Captura desde 2023-12-10 00-57-32](https://github.com/2shady4u/godot-sqlite/assets/1055216/75bb32d5-684a-4015-8fd8-f9b5ffb77976)

**Steps to reproduce:**
Declare a variable with type `SQLite`

**Minimal reproduction project:**

**Additional context**
this plugin worked fine when I had Godot 4.1 installed. Also, the plugin was installed from the Assets Store.

**Comment by scotmcp** [comment]
I have Godot-4.2 and I am not experiencing this same problem. Did you enable the plugin after installing it?

**Comment by shackra** [comment]
yes, I checked that before submitting the bug report and the plugin is enabled.

--
Jorge

**Comment by shackra** [comment]
I deactivated the plugin, restarted Godot 4.2, deleted the plugin, restared Godot again, installed the plugin from the asset store, restarted Godot, activated the plugin and restarted it again, the error persists:

```
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "SQLite" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "SQLite" not found.
  res://etc/database.gd:35 - Compile Error: Identifier not found: SQLite
  res://etc/decay_adder.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://etc/decay_adder.gd" with error "Compilation failed". (User)
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "SQLite" not found.
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "SQLite" not found.
  res://etc/database.gd:35 - Compile Error: Identifier not found: SQLite
  res://ui/decay_db_console.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2775 - Failed to load script "res://ui/decay_db_console.gd" with error "Compilation failed". (User)
```

**Comment by jgestiot** [comment]
I unsubscribed on GitHub and I still receive those messages

**Comment by shackra** [comment]
Okay, the issue is that the assets from the asset store are incompatible with NixOS. The way to workaround this, as the user, is to build the add-on yourself on NixOS.
