### ISSUE TITLE
Inserting Blobs?

### ISSUE THREAD

**Issue by charlesrwest** [2shady4u/godot-sqlite#16]
Hello!

Thank you guys for making this project!  I got really excited when I saw it because it looked like I could use it to export training data from Godot in my SQLite3 based exchange format.

I've run into a bit of an issue, however.  I need to export serialized screenshots as SQLite3 Blobs, but it looks like the current code converts everything into a string before submitting it.  This results in the following:

Code: 
Connection.insert_rows("Images",` [{"ImageId": NextImageId, "RunId": entry.RunId, "Timestamp": entry.Timestamp, "Data": entry.Data, "EntryAddedTimestamp": add_time}])

Result: 
INSERT INTO Images (ImageId,RunId,Timestamp,Data,EntryAddedTimestamp) VALUES (322,2,1593051530278.564209,[PoolByteArray],1593051531000);
 --> SQL error: no such column: PoolByteArray

I think you could get around this by using a prepared statement and bind in the library sqlite call, but it would require a bit of a change (though I think it also helps prevent sql injection attacks?).  If I may ask, is there a recommended way to insert a binary blob?

Thanks!

**Comment by 2shady4u** [comment]
Hello @charlesrwest !

Indeed, at the moment it is a bit tricky to insert raw data into the database using Godot-SQLite. 

The way to do it would be (haven't tested, but should work in theory):
`Connection.insert_rows("Images",` [{"ImageId": NextImageId, "RunId": entry.RunId, "Timestamp": entry.Timestamp, "Data": entry.Data.get_string_from_utf8(), "EntryAddedTimestamp": add_time}])`

This then uses [get_string_from_utf8](https://docs.godotengine.org/en/stable/classes/class_poolbytearray.html#class-poolbytearray-method-get-string-from-utf8)) to transform the PoolByteArray to an utf8-string which is storeable into the database as a BLOB.

Now... This ofc all depends on the size of those images... I can imagine that this becomes a bit unfeasible when they get huge.

I'll have to do some research on how the Python bindings achieve this sort of behaviour.

It would also help if you could supply a minimal project that demonstrates the issue.

**Comment by charlesrwest** [comment]
Hello @2shady4u !

It turns out that doing it the original way not only doesn't store the binary data but stores a TEXT value inside a column that is suppose to be binary (causing problems for the C++ reading code).  I was able to mostly get around the issue by using the "query" function directly and marking/converting the binary data to a hex encoding.

`		var insertion_string = "INSERT INTO Images VALUES (" +  str(NextImageId) + ", " + str(entry.RunId) + ", " + str(int(entry.Timestamp)) + ", X'" + entry.Data.hex_encode() + "', " + str(int(add_time)) + ");"
		Connection.query(insertion_string)`

On an unrelated note, I'm not sure your select rows function has a way to put in ORDER BY clauses.

**Comment by 2shady4u** [comment]
hello, I dont think the select rows function can support this functionality... you are better off just making your own query then and calling it using the query function. 

Sorry for my absence/delay in response, Ive been buried in work lately.

I see you found a way around the poolbytearray limitation? is it working in a satisfactory fashion?

**Comment by charlesrwest** [comment]
Hello!  No worries, things are fairly crazy for everyone just now.

That is what I ended up doing.

The hex work around is inefficient, but seems to be working OK for now.  Thanks.

**Comment by 2shady4u** [comment]
I was able to get inserting and loading blobs to work 🤔 
You can check it out on the '_blob-testing_'-branch.
Dunno if you still need this feature, but I'll see if I can fully implement it.

The stored texture in SQLiteStudio:
![Capture](https://user-images.githubusercontent.com/42484461/94030602-4a46f800-fdbe-11ea-8d26-abd921a2e682.PNG)

The original texture on the left, and the loaded texture on the right:
![Capture](https://user-images.githubusercontent.com/42484461/94040803-acf1c100-fdc9-11ea-9f30-7166475e0c65.PNG)

It requires a bit of a redesign of some core aspects of my SQLite bindings so I'll see how fast I can do this.
I'm also getting some memory leakage errors which I'll need to clean up 😱 

![Capture](https://user-images.githubusercontent.com/42484461/94041072-0ce86780-fdca-11ea-834a-e14ed3957008.PNG)

**Comment by charlesrwest** [comment]
It's no longer needed for that project (I eventually implemented my own cpp plugin so I could reuse a bunch of my existing code) but I have a new gd script project it would be really handy for (requires storing/retrieving audio samples).  Thanks!

**Comment by 2shady4u** [comment]
Implemented/resolved in version 2.1 as found in the [releases](https://github.com/2shady4u/godot-sqlite/releases/tag/v2.1) tab.
