### ISSUE TITLE
Add lint job

### ISSUE THREAD

**Issue by Ughuuu** [2shady4u/godot-sqlite#166]
A job that lints

Eg.:

https://github.com/V-Sekai/godot-whisper/blob/main/.github/workflows/lint.yml

**Comment by 2shady4u** [comment]
Hello @Ughuuu,

Adding some kind of formatting job makes sense.
I am currently time-restricted so I don't know when I will have time to work on this.

**Comment by 2shady4u** [comment]
Implemented in 06315508bf6979d82f45cf08d97ac238b5605519

Closing issue as a result 😄
