### ISSUE TITLE
How to store a Vector3?

### ISSUE THREAD

**Issue by scotmcp** [2shady4u/godot-sqlite#168]
Hi Shady,

I need to store a vector3, GDSqlite is complaining that is a data type 9 and that it can't handle it.

![image](https://github.com/2shady4u/godot-sqlite/assets/79280460/87c5ecdc-6728-414a-87fb-fb59d852b087)

The Vector3 is the "P" dictionary item in the Output frame.

How should this be accomplished?

**Comment by 2shady4u** [comment]
Hello @scotmcp 

SQLite only supports the following types:
- NULL
- INTEGER
- REAL
- TEXT
- BLOB

There's no Vector3 there so you'll have to be a bit more creative :)
As far as I see these are your options:
1. Store the Vector3 in its components instead. Meaning that you store X, Y and Z components of the Vector3 as REAL in the database instead.
2. Store the Vector3 as a string by using the 'var_to_str()'-method and load it out of the database by using the 'str_to_var()'-method.

**Comment by scotmcp** [comment]
That is what I ended up doing as a workaround, but ... I thought it could be saved as a blob. Splitting it up works, but I would recommend improving blob support. String just seems so .... inefficient. Ok thanks for the help mate.
