### ISSUE TITLE
Is it possible to do bulk update_rows

### ISSUE THREAD

**Issue by ibutab** [2shady4u/godot-sqlite#170]
My question is if it's possible to do bulk update_rows, in the documentation it's shown as one row but it's named row(s). With insert_rows it's possible to insert multiple rows. I can always loop the updates, but would prefer to do them in bulk since it's more efficient and cuts down on loading time.

Here is snippet from documentation/code: 
Change name of 'Amanda' to 'Olga' and her age to 30
db.update_rows(table_name, "name = 'Amanda'", {"AGE":30, "NAME":"Olga"})

**Comment by 2shady4u** [comment]
Hello @ibutab 

There should not be any reason why the command couldn't be used to update all rows that fit the condition.
For example (if using the db from the demo-project):

```godot
db.update_rows(table_name, "age > 25", {"SALARY":0})
```

Will set all the salaries of all the persons with an age above 25 to 0.
In this case that would be: "Paul", "Robert" and "Julia"

**Comment by ibutab** [comment]
> Hello @ibutab 
> 
> 
> 
> There should not be any reason why the command couldn't be used to update all rows that fit the condition.
> 
> For example (if using the db from the demo-project):
> 
> 
> 
> ```godot
> 
> db.update_rows(table_name, "age > 25", {"SALARY":0})
> 
> ```
> 
> 
> 
> Will set all the salaries of all the persons with an age above 25 to 0.
> 
> In this case that would be: "Paul", "Robert" and "Julia"
> 
> 
> 
> 

How could I do this with the case of say I want to update ID: 1 to amount: 100 and ID: 2 to amount 85. Where it's row specific and not a "general rule" like every x over y in your example.

**Comment by 2shady4u** [comment]
Well in that case you'll have to use the `query()`-method (or `query_with_params()`-method if you have unsanitized user input), as such:

```python
db.query("BEGIN TRANSACTION;")
db.query("UPDATE " + table_name " + " SET amount = 100 WHERE id = 1;")
db.query("UPDATE " + table_name " + " SET amount = 85 WHERE id = 2;")
db.query("END TRANSACTION;")
```

**Comment by Iscalej** [comment]
My solution for updating thousands of records in batches. Create a temporary table, add a trigger that updates the same record in the original table when a record is inserted, and insert the hundreds of records in batches with 'insert_rows(table,data)'. Drop the temporary table.
