### ISSUE TITLE
Syntax error thrown when ? used in query_with_bindings

### ISSUE THREAD

**Issue by VoxelTek** [2shady4u/godot-sqlite#171]
**Environment:**
 - OS: (K)Ubuntu 22.04.4 LTS
 - Godot version: 4.2.1
 - _godot-sqlite_ version: 4.3

**Issue description:**
Attempting to use `query_with_bindings` throws a syntax error:
```
   --> SQL error: near "?": syntax error
```

**Steps to reproduce:**
_(database already loaded into `responses_db`)_

```python
var possible_id = randi() % (2^14)
var check_user_ID : String = "SELECT * FROM ? WHERE User_ID = ?;"
var ID_params : Array = ["Users", possible_id]
var ID_check_success = responses_db.query_with_bindings(check_user_ID, ID_params)
``` 
Error thrown:
![image](https://github.com/2shady4u/godot-sqlite/assets/53562267/d257374d-a334-4d9c-b3a8-752b2edbb6db)

First error caused by this earlier code snippet:
```python
var get_count_string : String = "SELECT COUNT(*) FROM ?;"
var count_param : Array = ["Items"]
var item_count_success = items_db.query_with_bindings(get_count_string, count_param)
```

**Minimal reproduction project:**
Likely unnecessary, please inform if required.

**Additional context**
Installed godot-sqlite from Godot Asset Library, as was recommended.

**Comment by VoxelTek** [comment]
Ah, damn. That's annoying, but thanks for your help! I was hoping to avoid having to do it this way in order to ensure inputs are sanitised, but ah well. I appreciate your rapid response, and I'm glad this project exists!

**Comment by 2shady4u** [comment]
SQLite documentation: https://www.sqlite.org/cintro.html

Relevant section:
![image](https://github.com/2shady4u/godot-sqlite/assets/42484461/8cc613c1-8e50-4fb8-b2c5-6cad35f87ac6)
