### ISSUE TITLE
Doesn't work when exported

### ISSUE THREAD

**Issue by scotmcp** [2shady4u/godot-sqlite#176]
**Environment:**
 Linux Mint 21.3
Godot 4.2.2

**Issue description:**
When running the game in the editor, works fine
when running the game from the project manager screen, works fine
when I export the game, the gdsqlite doesn't seem to be touching the file at all, db reads and writes fail.

I copied the database to the target location manually. I tested that godot is writing files to the correct location (using a test FileAccess.WRITE function)

**Minimal reproduction project:**
It's a huge project.

**Comment by 2shady4u** [comment]
Hello @scotmcp,

If you export the game in DEBUG mode and run the exported game through the linux terminal, are there any errors reported?

**Comment by scotmcp** [comment]
CLosing this issue as not to do with gdsqlite, the problem lies elsewhere.....I got it working when running straight from terminal, it's when the server is started as a daemon that is causing the issue, and FileAccess.WRITE also breaks in this case, so it's something else entirely.

I would say it's permissions, but the daemons are running as root. :-/

Thank you!!!
