### ISSUE TITLE
Double precision support

### ISSUE THREAD

**Issue by Eerrikki** [2shady4u/godot-sqlite#178]
**Is your feature request related to a problem? Please describe.**
Yes, as mentioned in this [thread](https://github.com/Zylann/godot_voxel/issues/668):

**Describe the solution you'd like**
Please make SQLite work with double precision builds

**Comment by 2shady4u** [comment]
Hello @Eerrikki 

I've exported the plugin with the double precision flag. You can download the binaries here:
https://github.com/2shady4u/godot-sqlite/actions/runs/9650936482/artifacts/1633116555

(Actions here: https://github.com/2shady4u/godot-sqlite/actions/runs/9650936482)

You'll have to go into your local `addons/gdsqlite/gdsqlite.gdextension`-file and edit the paths of the debug and release Windows binary in that file.

Please tell me if that works or not.
And if not, please tell me (in enough detail) what you did 😄

**Comment by Eerrikki** [comment]
@2shady4u Thank you sooo much!! 
Your binary wizardry has brought joy!!  Thank you for sprinkling that extra precision dust and making this work :D

May your bugs be few and your codebase forever flourish!
