### ISSUE TITLE
offtopic question

### ISSUE THREAD

**Issue by l2toplist** [2shady4u/godot-sqlite#180]
hi, your plugin is just super, it works for version 3.5.3 without failure, so the question is, did your team happen to develop add-ons for other DBMSs? Like postgres or mysql for example?

I would love to support your project, but I still haven’t found a link where you can make a donation in cryptocurrency.

**Comment by 2shady4u** [comment]
Hello @l2toplist 
There's no "team" 😄 I am the only developer who is actively working on this plugin.
I didn't develop any other database plugins.

Regarding cryptocurrency donations; I don't event know if it is possible to set something like that up with Github 🤔

**Comment by l2toplist** [comment]
just leave your wallet in the description in ltc, bch or btc or whatever you choose and get coffee)

**Comment by 2shady4u** [comment]
Thanks for the offer! 😄 
But, I currently don't have a wallet nor am I planning to get one in the future 😋
