### ISSUE TITLE
Documentation for auto-increment

### ISSUE THREAD

**Issue by nightblade9** [2shady4u/godot-sqlite#19]
Hi! First, thanks so much for producing this package, it works really really well!

Second, could I bother you to add documentation for auto-increment columns into the README somewhere? I searched the code and found how it works.

For anyone reading this later: your column definition includes `"primary_key": true` and `"auto_increment": true` (without the primary key, you get an error).

**Comment by 2shady4u** [comment]
Hello! Sorry for taking a while to get to you!

If I'm correct in understanding your issue, adding an `"auto_increment": true` field to the column dictionary fails when the **primary_key** is not added (and thus implicitly set to _False_) as well?

A possible solution for me would be to automatically set the **primary_key** variable to _True_ whenever the **auto_increment** variable is found to be _True_?

Or might there be cases where setting **auto_increment** to _True_, while the **primary_key** is _False_ makes sense and is useful?

**Comment by nightblade9** [comment]
I think the code is fine as-is - if you try to set `auto_increment` without setting `primary_key`, you see some sort of error. That's fantastic.

All I'm suggesting is that you add something to `README.md` that includes `auto_increment`, so anyone who quickly wants to look up the usage can see an example (which also sets `primary_key`). That way, the usage will be obvious.

**Comment by 2shady4u** [comment]
@nightblade9 Hello! I finally found some time to expand the documentation a wee bit.

If possible, could it be possible to read the stuff I added and give your constructive criticism on this addition to the README?

**Comment by 2shady4u** [comment]
Okay! Thanks for your suggestion! :)
