### ISSUE TITLE
Query_with_bindings error in the documentation

### ISSUE THREAD

**Issue by devmark404** [2shady4u/godot-sqlite#193]
**Environment:**
 - OS:  Windows 10
 - Godot version: 4.3
 - _godot-sqlite_ version: 4.4

**Issue description:**
The following code from the documentation does not work, as it returns a result as shown in the following example

I think you cannot assign dynamic values ​​to column names from the query

readme
```
var query_string : String = "SELECT ? FROM company WHERE age < ?;"
var param_bindings : Array = ["name", 24]
var success = db.query_with_bindings(query_string, param_bindings)
# Executes following query: 
# SELECT name FROM company WHERE age < 24;
```

`[{ "?": "name" }, { "?": "name" }, { "?": "name" }]`

**Solution**
```
var query_string : String = "SELECT name FROM company WHERE age < ?;"
var param_bindings : Array = [24]
var success = db.query_with_bindings(query_string, param_bindings)
print(db.query_result)
# Executes following query: 
# SELECT name FROM company WHERE age < 24;
```

Or
```
var colum_name = "name";
var query_string : String = "SELECT "+colum_name+" FROM players WHERE score > ?;"
var param_bindings : Array = [1]
var success = db.query_with_bindings(query_string, param_bindings)
print(db.query_result)
```

I recommend replacing the examples with these

**Comment by 2shady4u** [comment]
Hello @devmark404!

You are correct!
I have updated/fixed the incorrect example in both the `README.md`-file and the documentation!
