### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by dydokamil** [2shady4u/godot-sqlite#2]
I'm having an issue trying to install this plugin

Steps to reproduce:
1. Go to Assets Library
2. Install godot-sqlite
3. Press install again, files get put into res://addons
4. Go to Project Settings then Plugins tab
5. Nothing is displayed on the list

Happens on both 3.1 stable and 3.2 RC1

**Comment by 2shady4u** [comment]
@dydokamil Hello! I'll try to replicate this error as soon as possible. Thank you for reporting. Be warned that I compiled this plugin for 3.1, so there might be issues for 3.2.. everything should work though for 3.1.... I'll get back to this as soon as possible!

**Comment by 2shady4u** [comment]
@dydokamil I changed the name of the config file, this should hopefully rectify the issue... I'm currently waiting for the change (rename of this file) to be approved by the Godot asset lib.

Will notify you whenever they approve these changes...

**Comment by 2shady4u** [comment]
@dydokamil should correctly work now, could you confirm this?
