### ISSUE TITLE
Attempted to call function new in base native script on a null instance

### ISSUE THREAD

**Issue by finepointcgi** [2shady4u/godot-sqlite#20]
When running the demo project i get 
![image](https://user-images.githubusercontent.com/12012300/103395733-ab891080-4afd-11eb-8f32-8bd41127987e.png)
as an issue when i attempt to run new(). It looks like the new function is missing?

I also am getting this with my own project, however I am not getting it with 1.7.

```

const SQLite = preload("res://addons/godot-sqlite/bin/gdsqlite.gdns")
var db
var dbLocation = "res://Datastore/test"
# Declare member variables here. Examples:
# var a = 2
# var b = "text"


# Called when the node enters the scene tree for the first time.
func _ready():
	_connectToDb()
	pass # Replace with function body.

func _connectToDb():
	db = SQLite.new() # fails here 
	db.path = dbLocation
	db.open_db
	db.query("""select * from MainTextboxText 
left join Button on Button.id = MainTextboxText.Button1ID or button.id = MainTextboxText.Button2ID or Button.id = MainTextboxText.Button3ID
where MainTextboxText.ID = 1""")
	var dict :Dictionary = Dictionary() 
	dict = db.query_result
	get_tree().get_root().get_node("scene_main_node/control").storyState = db.query_result
```

Thanks,
Mitch

**Comment by 2shady4u** [comment]
Hello @mitchelldmccollum 

It seems that is due to the fact that I am creating libraries exported in debug mode instead of release mode.
I'll update the libraries to the release target and I'll see if the problem persists.

In fact it is quite similar to this:
https://github.com/godotengine/godot-git-plugin/issues/9

Greetings! And apologies for this bug!

**Comment by 2shady4u** [comment]
Okay, seems that switching to the release target does the job, I'll update build scripts and will have to push an update to the asset library.

Thanks for catching my error! I'll close this whenever the guy/gals at the asset library accept the new version!

**Comment by 2shady4u** [comment]
I updated all binaries with their release equivalent and hopefully this should fix the issue... (it does on my end!)

We'll have to wait a few days for the asset library update to be approved though 🤷

**Comment by mitchelldmccollum** [comment]
No problem thanks for fixing it so quickly! I just put a video out on this library and sqlite and I has someone message me saying it was broken!

**Comment by 2shady4u** [comment]
A bit of an inconvenient time for me to break it then 😞 

Now you made me curious; is that video available for public?

**Comment by finepointcgi** [comment]
Yes it is publiv, however Im not going to tell  you to add it to your repo unless you want to. I dont go though all the options mainly just insert and run query.
https://www.youtube.com/watch?v=HG-PV4rlzoY

**Comment by finepointcgi** [comment]
I have downloaded the newest version and it does work now! I will close this issue!

Thanks,
Mitch
