### ISSUE TITLE
Support for full SQL?

### ISSUE THREAD

**Issue by MrSmite** [2shady4u/godot-sqlite#21]
There is [another godot-sqlite project](https://github.com/khairul169/gdsqlite-native) on github that supports full SQL such as _CREATE_DATABASE_, _CREATE_TABLE_, and _Prepared statements_. Problem is that project hasn't had any activity for two years.

I looked through your code and examples but don't see any indication if your library supports standard SQL or if it is limited to using dictionaries. You've done a great job so far, I was just wondering what the roadmap looks like for a full-functioning SQLite interface for Godot 4.

**Comment by 2shady4u** [comment]
If by "standard" SQL you mean if this project supports the use of directly querying with strings, then the answer is yes.
The convenience "wrapper" functions such as (for example) `create_table()` and `insert_row()` can also be fully realized by writing the query yourself.

**Example A:**
```
var table_dict : Dictionary = {
"id": 
    {"not_null": true, "data_type":"int", "primary_key":true}, 
"description": 
    {"data_type": "text"}
}
db.create_table("inventory", table_dict)
```

**_is (or should be) fully equivalent to:_**
```
db.query("CREATE TABLE IF NOT EXISTS inventory (id INTEGER PRIMARY KEY NOT NULL, description text);")
```

**Example B:**
```
var row_dict: Dictionary = {
"id": 0,
"description": "A cool trinket"
}
db.insert_row("inventory", row_dict)
```

**_is (or should be) fully equivalent to:_**
```
db.query("INSERT INTO inventory (id,description) VALUES (0,'A cool trinket');")
```

Basically you can ignore the convenience wrapper functions and only use the "open_db", "query", and "close_db" functions if that suits your own purposes better.

At the moment I'm currently not using _prepared statements_ but using the [sqlite3_exec()](https://www.sqlite.org/c3ref/exec.html)-function instead. This will change in the next release which will see the introduction of BLOBS and proper parameter bindings. (You can check out my current work on this in this [branch](https://github.com/2shady4u/godot-sqlite/tree/feature-add-blobs)). Next big point on the roadmap is the possibility to access databases packaged in the godot .PCK.

Regarding the `CREATE_DATABASE`-query, this functionality is not part of my current road map. But can probably already be implemented by using the `query()`-function in a clever way.

**Comment by MrSmite** [comment]
Great, thanks. I guess "standard SQL" wasn't really a good choice of words  :) I was referring to SQL such as INNER JOIN, UPDATE, DELETE ... etc.

There is a fork of the repo I linked earlier that provides encryption using sqlite_key3() operations to open the database with a password. I noticed the user has an older version of the sqlite3 header (3.31) and in yours (3.34), sqlite_key3() does something different.

Unfortunately according to [this page](http://www.hwaci.com/sw/sqlite/see.html), the license for encryption module is $2000
Fortunately according to [this page](https://stackoverflow.com/a/5877130), there are several open source projects.

I know encryption isn't that important in the scope of Godot use but it would be nice to be able to protect game assets.

**Comment by 2shady4u** [comment]
@MrSmite 

All SQLite query syntax should be available by directly using the _query()_-function. If there are important commands that are failing to execute please do open another issue. 

I've looked into encryption at some point because some users (such as you right now) were requesting it. 
I think (it has been a while) that I went through a few of them before concluding that it **wasn't** a simple case of just adding some additional C-files and would require some more work.

I can look into adding it at some point in the future, but it would be after I implement BLOBS, parameter bindings and buffering of packaged databases. (this might take a while though!)

**Comment by 2shady4u** [comment]
SQLeet seems to be the best candidate to implement at some point:
https://github.com/resilar/sqleet

(Putting this here, mostly for my future self)

**Comment by MrSmite** [comment]
Considering sqleet is public domain, wouldn't it be possible to merge a clone of that repo with your project?
