### ISSUE TITLE
Struggling Coder

### ISSUE THREAD

**Issue by Airoswag** [2shady4u/godot-sqlite#22]
Hey, I am trying to make a game incorporating the sqlite, but it appears there is an issue with the second to last line in the last function called savescore, here is the entire code for the script, this is my first time sharing in github so Im not sure how else to present it.
extends Node

const SQLite = preload("res://addons/godot-sqlite/bin/gdsqlite.gdns")
var db
var db_name := "res://data/test"
var PlayStats = PlayerStats
var scoretable_name := "ScoreTable"
var playertable_name := "PlayerTable"
var ids := []
var names := []
var playerids := []
var batskilled := []
var currentname
var finalscore 

signal output_received(text)

func _ready():
	cprint("Under Construction")
	var newscore = PlayerStats.score
	print(newscore)
	var stringscore : String = String(newscore)
	cprint("Previous Score: "+stringscore)

func output_scores():
	db = SQLite.new()
	db.path = db_name
	db.verbose_mode = true 
	#var select_condition: String = ""
	#var selected_array: Array = db.select_rows(scoretable_name, select_condition, ["*"])
	#cprint("condition: " + select_condition)
	#cprint("result: {0}".format([String(selected_array)]))

func cprint(text: String) -> void:
	print(text)
	emit_signal("output_received", text)

func create_tables():
	db.create_table(playertable_name,{
	"id":{"data_type": "int", "primary_key":true,"not null": true},
	"name":{"data_type": "text", "not_null":true,},
	"scoretable":{"data_type": "int", "foreign_key": "scoretable.id","not_null": true}
	})

	db.create_table(scoretable_name,{
	"id":{"data_type": "int", "primary_key": true, "not_null": true},
	"turnslived":{"data_type": "int","not_null":true}
	})

func update_scores(score):
	finalscore = score
	print("The score is now: "+ str(score))
	cprint(score)

func _on_LineEdit_text_entered(playername):
	print("The name: "+ str(playername) + " will be stored")
	currentname = playername
	cprint("Name: " + playername)
	savescore(currentname)

func savescore(name):
	db = SQLite.new()
	db.path = db_name
	db.verbose_mode = true
	db.drop_table(playertable_name,scoretable_name)
	create_tables()
	db.open_db()
	db.insert_rows(playertable_name, [{"id" : 0, "name" : name, "scoretable" : 0}])
	db.insert_rows(scoretable_name, [{"id" : 0, "turnslived" : finalscore}])
	var select_condition: String = ""
	var selected_array:Array = db.select_rows(playertable_name, select_condition, ["*"])
	cprint("name:   {0}".format([typeof(selected_array[0]["name"])]))
	db.close_db()

**Comment by 2shady4u** [comment]
Hello @Airoswag 

Easiest way to correctly format code is to use three backticks ``` before and after the code, like this:

\`\`\`gdscript
func _ready():
  cprint("Under Construction")
  var newscore = PlayerStats.score
  print(newscore)
  var stringscore : String = String(newscore)
  cprint("Previous Score: "+stringscore)
\`\`\`

This will end up looking like this:

```gdscript
func _ready():
  cprint("Under Construction")
  var newscore = PlayerStats.score
  print(newscore)
  var stringscore : String = String(newscore)
  cprint("Previous Score: "+stringscore)
```

The *gdscript* tag tells Github that the code contained between brackets is written in GDScript and should receive the proper coloring highlights.

Regarding your code, I don't see anything wrong at first glance.
I also can't run your code since I don't have the *PlayerStats* object available in my code.
Could it be possible to give me the following:
- What OS are you running this code on? (Linux, Windows, MacOS, ...?)
- What version of Godot are you using?
- What is actual error you are getting in the console? Could you printscreen or copy the contents of your Godot console screen?
- Could you give me either a ZIP of your project or at least a version that runs without relying on any dependencies (Like *PlayerStats* ?) Just so I can easily test this on my own PC.

Cheers XXX

**Comment by Airoswag** [comment]
1. I am using Windows
2.  3.2.3 Stable I believe
3.  
![image](https://user-images.githubusercontent.com/71433384/103672307-085c4f00-4f74-11eb-84aa-3b852b0bacd2.png)
4. The game file is waaaaaaay too big, but basically the player stats just stores a score so you can sub 0.

**Comment by 2shady4u** [comment]
Okay @Airoswag , it seems that you didn't open your database before creating the tables and that is most likely the cause of the error. Also are you sure the "data/"-folder exists? If the data-folder doesn't exist, the plugin won't be able to open or create the database.

```gdscript
func savescore(name):
  db = SQLite.new() # Create a new database connection
  db.path = db_name # set to the path where the database is to be created or opened
  db.verbose_mode = true # Print a bunch of useful stuff for debugging purposes
  db.open_db() # FIRST open the database connection BEFORE dropping and creating tables!

  db.drop_table(playertable_name,scoretable_name)
  create_tables()
  db.insert_rows(playertable_name, [{"id" : 0, "name" : name, "scoretable" : 0}])
  db.insert_rows(scoretable_name, [{"id" : 0, "turnslived" : finalscore}])
  var select_condition: String = ""
  var selected_array:Array = db.select_rows(playertable_name, select_condition, ["*"])
  cprint("name: {0}".format([typeof(selected_array[0]["name"])]))
  db.close_db()
```

So:
- Make sure that the "res://data/"-folder actually exists. Because the plugin won't create this folder (will probably change in the future)
- FIRST open the database connection before attempting to create and/or drop tables

**Comment by Airoswag** [comment]
Thank You So much, it appears to work now, the issue was with the folder, it never existed and once I made it, it worked.
