### ISSUE TITLE
[Suggestion] Instead of having a script to copy data to the build folder(android)

### ISSUE THREAD

**Issue by Thebas** [2shady4u/godot-sqlite#30]
Instead of : https://github.com/2shady4u/godot-sqlite#how-to-export
One can add the folder to the resources in the export screen. Like so:

![image](https://user-images.githubusercontent.com/5076514/106386420-2c754980-63d5-11eb-87b8-d8f8d4ecdde9.png)

**Comment by 2shady4u** [comment]
Small disclaimer: This part of the README is horribly old and I've been wanting to rewrite it after I implement a proper virtual file system so databases can be accessed inside of the PCK.

Now, I might be wrong, but exporting the files/folders in that way won't work. The database will packaged (by Godot) into the PCK-archive after which the SQLite bindings won't be able to access the database anymore...

I'm interested to see if you tested the above method?

**Comment by Thebas** [comment]
Yes, I've been working with it!
We still need to keep the check to copy the data to the user:// folder.
This change only removes the need to copy stuff by script into the build folder.

**Comment by 2shady4u** [comment]
So as long as you indeed copy the database to the user:// this will indeed work.

In cases where you don't want to copy the entire database and the database thus remains somewhere in res://, this won't work. (YET)

**Comment by Thebas** [comment]
Odd. I'm testing locally(linux) and it works fine.

**Comment by Thebas** [comment]
Oh! you mean Android + res://!
Ok, I confirm it doesn't work.

**Comment by Thebas** [comment]
My suggestion is: Remove the export_data.gd and associated explanations in the Readme as it is not needed if you substitute them by this property shown in the screenshot.
IMHO it is more elegant and less cumbersome.
The final decision is yours tho.
:)

**Comment by 2shady4u** [comment]
I'll have to do some tests for this, I'll get back to you with whatever I come up with.

**Comment by 2shady4u** [comment]
@Thebas This would only be for Android? 🤔 
Because on Windows this doesn't work at all 🤷

**Comment by 2shady4u** [comment]
Okay, I've added an additional disclaimer to the README.md, I hope this is sufficient for now!
(until I figure out a proper VFS for loading databases)
