### ISSUE TITLE
Error calling update_rows/select_rows with PoolByeArray/BLOB as input, insert_rows works fine though

### ISSUE THREAD

**Issue by tommasodargenio** [2shady4u/godot-sqlite#32]
I was using this plugin already before the 2.1 and the queries with blobs / raw data were not working. With 2.1 my insert works well however the updates still don't.

I download an image from a web server, this comes as PoolByteArray type. When using the insert_row method it works fine and I can see the image in the database, however, when using the update_rows method I get this error in the debug window:

```
E 0:00:03.778   bool __cdecl godot::SQLite::query_with_bindings(class godot::String,class godot::Array):  --> SQL error: no such column: PoolByteArray
  <C++ Source>  src\gdsqlite.cpp:153 @ bool __cdecl godot::SQLite::query_with_bindings(class godot::String,class godot::Array)()
  <Stack Trace> database.gd:76 @ _update_data_ID()
                main.gd:184 @ update_sub_pic_alt()
                main.gd:159 @ load_sub_pic_alt()
                main.gd:127 @ load_sub_details()
                main.gd:104 @ _on_subs_loaded()
                google.gd:224 @ _load_user_subs_alt()
```

I've verbose mode on so looking at the query the plugin creates, it looks like this

```
UPDATE subscriptions SET title='test',description='test',channelId='UC5A1ASXDA132',thumbnailStandard=[PoolByteArray],thumbnailMedium=[PoolByteArray]' WHERE  id = 336;END TRANSACTION;
```

I was wondering if this is a bug, or something I'm doing wrong and how can be fixed?

Thanks

**Comment by 2shady4u** [comment]
Smells like a bug...
Could you test this with 2.2? 
Probably wont change anything, but who know?

I'll try to do a test this weekend in an attempt to replicate the issue.

**Comment by tommasodargenio** [comment]
Just tested on 2.2, I'm afraid I get the same error. Let me know if you want me to test further.

**Comment by 2shady4u** [comment]
I'm having the same issue in a simple example:

![image](https://user-images.githubusercontent.com/42484461/107085632-0a2a6400-67f9-11eb-9302-06c950ed11f4.png)

I know what is causing the error... (I'm not calling `query_with_bindings()`) but I won't have time to fix it immediately.

A current work-around is to do the following:
`db.query_with_bindings("UPDATE subscriptions SET thumbnailStandard = ? WHERE  id = 336;", [tex_data])`

with tex_data being a Godot PoolByteArray-variable

**Comment by tommasodargenio** [comment]
Glad you found the bug, no worries about updating take your time. Your workaround actually worked without a problem and I can continue my work. Thanks a lot! 

I'll leave it up to you to close this or not in case you want to keep it here until the bug is solved and reference the commit back.

**Comment by 2shady4u** [comment]
I'm looking at the best way to implement this in the most elegant way possible.
I'm just wondering if a BLOB will ever be used as an update-condition, like this:

```
UPDATE subscriptions SET title='test2' WHERE  thumbnailMedium=[PoolByteArray];
```

Would that be useful in some cases? And if yes, is this an edge-case or something that might be applied more generally?
🤔

**Comment by tommasodargenio** [comment]
I wouldn't personally use a blob in a WHERE clause in general (not very efficient and quite memory expensive), but there might be a lot of cases where this is something the dev would like to do. I don't think that UPDATE is the place where you would use such a thing, more like in a SELECT.

my 2 cents :)

**Comment by 2shady4u** [comment]
That's probably gonna need some changes in the amount and type of the input arguments of those functions, which will mess up backwards compatibility.

I'll leave this issue open for now for other people that have this exact same issue can read about the work-around.
No idea when I'll fix this though...

**Comment by 2shady4u** [comment]
I added the possibility to include BLOBs in an `update_rows()`-statement.
Also I've decided not to allow PoolByteArray (and bindings as result) in the conditional string of `update_rows()` & `select_rows()` since that would require breaking compatibility and can easily be circumvented with the work-around described above.

For the moment I'm considering this issue to be closed.
