### ISSUE TITLE
EditorPlugin

### ISSUE THREAD

**Issue by mabelair88** [2shady4u/godot-sqlite#35]
I have godot engine v 3.2.3. I add the SQlite plugin 2shady4u.
I am getting an error on start of the godot Engine
"Impossible de charger le script de l'addon depuis le chemin : « res://addons/godot-sqlite/godot-sqlite.gd ». Le type de base n'est pas EditorPlugin."
This is the addon godot-sqlite.gd is not working with EditorPlugin.
I can not solve this problem, can you help me.
bestr regards,
MichelB

**Comment by 2shady4u** [comment]
Hi @mabelair88

Could you tell me the following:
- your OS (windows, linux, macos)
- the version of the plugin (as found in plugin.cfg)
- Did you activate/deactivate the plugin in the ProjectSettings?

**Comment by mabelair88** [comment]
hi Piet Bronders,

I am on win10,*  Plugin **v**er*sion="2.2", when I try to activate the
plugin, I receive the fault message described before. I am not able to
activate the Plugin.

MichelB


Le ven. 19 févr. 2021 à 13:59, Piet Bronders <notifications@github.com> a
écrit :

**Comment by 2shady4u** [comment]
Here's a video showing the install process for Windows 10 with Godot 3.2.3:

https://user-images.githubusercontent.com/42484461/108568686-ce1ff480-730a-11eb-88d2-0bba6c77f0ae.mp4

As you can see I don't seem to get this error? 
Please tell me what is different in your case?
Is the process the same for you?

**Comment by mabelair88** [comment]
Yes, it is working.
I had to remove all addons in my tree. And also remove the addon in the
demo. I did reboot my CPU, and started the procedure you sent me.
Thank you very much for your help. And have a nice day.
best regards,
MichelB


Le ven. 19 févr. 2021 à 17:34, Piet Bronders <notifications@github.com> a
écrit :

**Comment by 2shady4u** [comment]
Okay!
If you run into any other issues please feel free to open another issue :D
