### ISSUE TITLE
Double log messages with verbose_mode=true

### ISSUE THREAD

**Issue by mrimvo** [2shady4u/godot-sqlite#40]
Hello there,

this is more of a question. When working with the plugin, and setting `db.verbose_mode = true`, I get every statement 2x. Is this intended behavior?

```
SELECT uid from users WHERE uid = 4026253021;
SELECT uid from users WHERE uid = 4026253021;
 --> Query succeeded
BEGIN TRANSACTION;
BEGIN TRANSACTION;
 --> Query succeeded
UPDATE users SET avatar=...<snip>
UPDATE users SET avatar=...<snip>
```

Thank you for this amazing plugin, it helps a lot :)

**Comment by 2shady4u** [comment]
Hi @mrimvo 

This is intended behaviour and is useful when using parameter bindings.
For example, in the demo project, the console logs both the original query and the finished query (with parameters added)

**Comment by mrimvo** [comment]
Thank you for clarification :)
