### ISSUE TITLE
Noob Question: Is it possible to open db in GUI?

### ISSUE THREAD

**Issue by bananabrann** [2shady4u/godot-sqlite#45]
Hey y'all! 

I'm new to Godot and this SQLite plugin, and I'm running into some issues with opening the database in a GUI. I have a strong hunch I'm misunderstanding the plugin, or missing some basic knowledge.

I'm making my little game as a side project to learn something new. The goal that I have in mind is that there's an items table that the game would read from. From Godot's code, I wouldn't really manipulate items in this table, it would act mostly read-only. To edit those items, I figured I could just open it in a GUI and add some test items and columns, then reference those via what the docs say in the plugin.

- Should I be able to connect to the db outside of Godot?
- If so... How would I go about that? My client doesn't see any executables in bin/ that it can open from. (Is that even the correct way?)

Appreciate any response, thank you! :smiley:

**Comment by 2shady4u** [comment]
Hello @bananabrann 

If I'm understanding you correctly, you are searching for an external database editing tool?
I highly recommend using [SQLiteStudio](https://sqlitestudio.pl/) for that purpose.

When you open a database using the plugin (and it doesn't exist yet) it creates a new `*.db`-file at the "path"-variable.
This `*.db `file can then be opened and edited by SQLiteStudio.
Alternatively you can also just create a new database using SQLiteStudio from scratch and then open/edit it in Godot.
(Or a combination of both ofc)

**Comment by bananabrann** [comment]
Oh wow, I feel dumb. I had assumed the plugin created the database on creation. I didn't even consider that possibility in my head. Thank you! @2shady4u  :smile:
