### ISSUE TITLE
Is this thread-safe?

### ISSUE THREAD

**Issue by shivambromax** [2shady4u/godot-sqlite#48]
So I am using this module as db for my server, 

Everytime a client requests something a new thread is made which accesses the same database.
So after a while the server runs, server crashes & Sends this error
![image](https://user-images.githubusercontent.com/69040506/115145436-27887380-a06f-11eb-9a75-87f935a1db73.png)

hopefully theres something you know about this?

Or should I try using mutexes?

**Comment by 2shady4u** [comment]
According to this:
https://sqlite.org/threadsafe.html
The default value for thread safety is "serialized", which allows threads.

Are you using the same database connection in all of those threads? Or do you create a new database object in each thread? (second option is preferred)

I don't have any experience using SQLite in threads 😞 , but there's no reason why it shouldn't work according to the SQLite docs.

**Comment by shivambromax** [comment]
> According to this:
> https://sqlite.org/threadsafe.html
> The default value for thread safety is "serialized", which allows threads.
> 
> Are you using the same database connection in all of those threads? Or do you create a new database object in each thread? (second option is preferred)
> 
> I don't have any experience using SQLite in threads 😞 , but there's no reason why it shouldn't work according to the SQLite docs.

I am using the same database in the threads, but yeah I used mutex lock & unlock whenever thread needs to use it, & its fixed now, thanks for replying!

**Comment by shivambromax** [comment]
This is thread safe, database just needs to be mutex-ed
