### ISSUE TITLE
Better home page description

### ISSUE THREAD

**Issue by txj-mssl** [2shady4u/godot-sqlite#49]
I am an amateur who has never touched a database before, and I couldn't use it at all after reading the introduction below the home page, until I read the sample code provided and understood a little.

**Comment by 2shady4u** [comment]
@txj-mssl hello!

With what did you have trouble?
- Understanding how databases work? (SQLite in this case)
- Understanding how this plugin should be used in Godot?

What would you propose would have to be added to the README to make it easier?

**Comment by 2shady4u** [comment]
@txj-mssl I added an additional section that links to an introductory video tutorial.

**Comment by txj-mssl** [comment]
thanks ，I'll go and have a look. After I finish my study, I'll give feedback

**Comment by 2shady4u** [comment]
Hello @txj-mssl 
Do you have any feedback regarding the current state of the home page description?
Is there still something missing according to you? Or is the updated version of the README.md sufficient according to you?

**Comment by txj-mssl** [comment]
At present, I have not.    When I think about it, I will tell you.

**Comment by 2shady4u** [comment]
Closing this one due to inactivity and because the README.md has been (in my opinion) properly extended with additional information on how to set up Godot-SQLite on your device.

If you do not agree or you have extra information, please feel free to reopen this issue :D
