### ISSUE TITLE
Server entry is missing in gdsqlite.gdnlib

### ISSUE THREAD

**Issue by txj-mssl** [2shady4u/godot-sqlite#50]
I have learned a little knowledge about database these days, and understood some simple operations of database.
I try to write a simple project about saving the account and password in the database after the user registers.
I bought a Linux cloud server from Alibaba cloud and tried to deploy the server on it. When I tried to run it, I reported the following error.
I use winscp to upload the file to the server root. The directory structure is：
libgdsqlite.so[file]
data{folder]database.db[file]
server.pck
server.64

After running, the error is reported as：
ERROR: init_library: Condition "lib_path.length() == 0" is true.
   At: modules/gdnative/nativescript/nativescript.cpp:1459.

I tried to run it in local editing and found no problems

**Comment by txj-mssl** [comment]
[server.zip](https://github.com/2shady4u/godot-sqlite/files/6565897/server.zip)
[client.zip](https://github.com/2shady4u/godot-sqlite/files/6565899/client.zip)

**Comment by txj-mssl** [comment]
The above is the source code

**Comment by txj-mssl** [comment]
Alibaba Cloud Linux 2.1903 LTS 64

**Comment by txj-mssl** [comment]
Cloud server is Alibaba Cloud Linux 2.1903 LTS 64

**Comment by 2shady4u** [comment]
Hello @txj-mssl !

Seems like the "Server" entry in the "gdsqlite.gndlib"-file got deleted at some point 😞 
You can fix this issue by adding the entry yourself to this file, like so:
```
[general]

singleton=false
load_once=true
symbol_prefix="godot_"
reloadable=false

[entry]
Server="res://addons/godot-sqlite/bin/x11/libgdsqlite.so"

Android.armeabi-v7a="res://addons/godot-sqlite/bin/android/armeabi-v7a/libgdsqlite.so"
Android.arm64-v8a="res://addons/godot-sqlite/bin/android/arm64-v8a/libgdsqlite.so"
Android.x86="res://addons/godot-sqlite/bin/android/x86/libgdsqlite.so"
HTML5.wasm32="res://addons/godot-sqlite/bin/javascript/libgdsqlite.wasm"
OSX.64="res://addons/godot-sqlite/bin/osx/libgdsqlite.dylib"
Windows.64="res://addons/godot-sqlite/bin/win64/libgdsqlite.dll"
X11.64="res://addons/godot-sqlite/bin/x11/libgdsqlite.so"
iOS.armv7="res://addons/godot-sqlite/bin/ios/armv7/libgdsqlite.a"
iOS.arm64="res://addons/godot-sqlite/bin/ios/arm64/libgdsqlite.a"

[dependencies]
Server=[  ]

Android.armeabi-v7a=[  ]
Android.arm64-v8a=[  ]
Android.x86=[  ]
HTML5.wasm32=[  ]
OSX.64=[  ]
Windows.64=[  ]
X11.64=[  ]
iOS.armv7=[  ]
iOS.arm64=[  ]
```
As discussed here as well:
https://godotengine.org/qa/63890/how-to-open-gdnative-projects-with-headless-server-godot

**Comment by txj-mssl** [comment]
I modified that file as you said, and then ran it again, reporting the following error：
ERROR: open_dynamic_library: Condition "!p_library_handle" is true. Returned: ERR_CANT_OPEN
   At: drivers/unix/os_unix.cpp:415.
ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:502.
ERROR: init_library: No nativescript_init in "res://addons/godot-sqlite/bin/x11/libgdsqlite.so" found
   At: modules/gdnative/nativescript/nativescript.cpp:1482.

**Comment by txj-mssl** [comment]
I still don't quite understand

**Comment by 2shady4u** [comment]
> 
> 
> I modified that file as you said, and then ran it again, reporting the following error：
> ERROR: open_dynamic_library: Condition "!p_library_handle" is true. Returned: ERR_CANT_OPEN
> At: drivers/unix/os_unix.cpp:415.
> ERROR: get_symbol: No valid library handle, can't get symbol from GDNative object
> At: modules/gdnative/gdnative.cpp:502.
> ERROR: init_library: No nativescript_init in "res://addons/godot-sqlite/bin/x11/libgdsqlite.so" found
> At: modules/gdnative/nativescript/nativescript.cpp:1482.

Yes, so now it is able to correctly find the dynamic library 👌
There still seems to be an issue with loading the dynamic library though. 

The issue might be that the glibc version of the Alibaba cloud is too old, as discussed in this closed issue: https://github.com/2shady4u/godot-sqlite/issues/36

Two things to try:
1. Try to find out the glibc version of your Alibaba Cloud LTS machine, by running in the console/terminal:
`ldd --version`
On the server linux machine so you can get the version of your glibc and report it back here.

2. Replace the `libgdsqlite.so`-file by the legacy version (that supports older versions of glibc) as downloadable here:
https://github.com/2shady4u/godot-sqlite/actions/runs/819913518
Download the X11-legacy file as simply replace the `libgdsqlite.so`-file with this legacy file.

More information:
https://godotforums.org/discussion/26366/trouble-getting-gdnative-library-to-work-on-ubuntu

**Comment by txj-mssl** [comment]
I used this command to query and found that it seems to be 2.17

**Comment by 2shady4u** [comment]
> 
> 
> I used this command to query and found that it seems to be 2.17

That is a bit problematic... could you see if it is possible to upgrade your glibc to a later version of this server?
For the default `libgdsqlite.so`-file you will need at least glibc version 2.28
For the legacy version of the `libgdsqlite.so`-file you will need at least glibc version 2.23

Another possibility is to recompile the library using an older glibc version (<= 2.17), but I currently don't have a device available that has this older version.

**Comment by txj-mssl** [comment]
Thank you very much. The problem has been solved. I changed the version of the cloud server. His glibc version is 2.32, and my program has been running normally. I don't know anything about Linux and C + +. Thank you very much for your help.

**Comment by 2shady4u** [comment]
Leaving this issue open until I have time to correctly re-add the Server entry into the gdnlib-files.

**Comment by 2shady4u** [comment]
The missing Server entry has been added in the `dev`-branch and will be included in the next release!
