### ISSUE TITLE
Does not work on android with custom template

### ISSUE THREAD

**Issue by spyr0s** [2shady4u/godot-sqlite#53]
**Environment:**
 - OS: macOs
 - Godot version: 3.3.2
 - _godot-sqlite_ version: 2.4

**Issue description:**
When building for android using a custom template i got the error
Can't open dynamic library: libgdsqlite.so, error: dlopen failed: library "libgdsqlite.so" not found.
and the plugin does not work

**Steps to reproduce:**
Install android custom templates and export the project for android

**Comment by 2shady4u** [comment]
Hello @spyr0s 

Just to confirm: exporting for Android without using a custom template works without any problems?

**Comment by spyr0s** [comment]
Yes, it works fine.
I foxed it by copying the contents of 
/addons/godot-sqlite/bin

inside 
android/build/libs/(debug|release) folders 
but i'm sure that's not an optimal way

Tried adding the paths in build.gradle
```
debug.jniLibs.srcDirs = [
            'libs/debug',
            '../../addons/godot-sqlite/bin/android'
//DIR_JNI_DEBUG_BEGIN
//DIR_JNI_DEBUG_END
        ]
        release.jniLibs.srcDirs = [
            'libs/release',
	    '../../addons/godot-sqlite/bin/android'
```

with no luck

**Comment by 2shady4u** [comment]
Latest Dev snapshot seems to address some of these issues that you are having?

![image](https://user-images.githubusercontent.com/42484461/127483245-ca9d5bb9-e17b-4c3f-8e0f-368dcc647a03.png)

Relevant PR:
https://github.com/godotengine/godot/pull/49911

Could you check if you have the same issue with Godot 3.4?

**Comment by spyr0s** [comment]
Yes, it worked with godot 3.4 beta 2 
👍

**Comment by 2shady4u** [comment]
@spyr0s I'll leave this issue open until Godot 3.4 has been released.
would you be willing to give a small code snippet or explanation on how to add the plugin to custom Android builds?

Are there any other issues that haven't been solved by Godot 3.4?

**Comment by spyr0s** [comment]
I just copied the folders
`arm64-v8a`
`armeabi-v7a`
`x86`

from
`addons/godot-sqlite/bin/android`
to
`android/libs/debug` and
`android/libs/release`

**Comment by 2shady4u** [comment]
@spyr0s with the release of the new Godot v3.3.3 this issue should now have been fixed by the engine.
Can you confirm this? and if yes, can you close this issue?

**Comment by 2shady4u** [comment]
I'll consider this issue closed for now...
Feel free to re-open this issue if the problem persists.
