### ISSUE TITLE
Cannot create table with column name 'From'

### ISSUE THREAD

**Issue by Toshiwoz** [2shady4u/godot-sqlite#54]
**Environment:**
 - OS: Windows
 - Godot version: 3.3.2 stable
 - _godot-sqlite_ version: 2.5

**Issue description:**
If you try to create a table with a column name equal to the keyword From, it fails, having it considered as a wrong syntax.

**Steps to reproduce:**
In verbose mode this is the statement it's trying to run.

```
CREATE TABLE IF NOT EXISTS ReceiveText 
(Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
,EventId INTEGER NOT NULL
,From text
,Message text
,Channel text);
```
If you simply add single quotes to the statement, it works:

```
CREATE TABLE IF NOT EXISTS ReceiveText 
(Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
,EventId INTEGER NOT NULL
,'From' text
,Message text
,Channel text);
```

**Minimal reproduction project:**

```
var table_name := "characters"
var table_dict : Dictionary
table_dict["Id"] = {"data_type":"int", "default": 0}
table_dict["From"] = {"data_type":"text", "default": "'Long John'"}
db.create_table(table_name, table_dict)
```

**Additional context**
No other info.

**Comment by 2shady4u** [comment]
Does this query work when used in https://sqliteonline.com/ ? This might just be an SQLIte thing that I'm unable to change/fix.

**Comment by Toshiwoz** [comment]
It does fail, it is indeed an SQLite issue.
I was able to workaround the problem by adding single quotes to the table column name in the dictionary.
Something like this:

```
var table_name := "characters"
var table_dict : Dictionary
table_dict["Id"] = {"data_type":"int", "default": 0}
table_dict["'From'"] = {"data_type":"text", "default": "'Long John'"}
db.create_table(table_name, table_dict)
```

Notice the single quotes inside here `table_dict["'From'"]`.
I don't know if it's a good idea or not to integrate that in the plugin's code, it happens with any columns that happen to cotain an SQL keyword:

- to
- from
- select
- asc

I've created an array of prohibited columns:

`var forbidden_columns := ["From", "To", "Group", "By", "Sort", "Asc"]`

Whenever I catch them I add those quotes, and we're good, but I guess that even adding them always would do the trick.

**Comment by 2shady4u** [comment]
You can find a full list of protected SQLite keywords here:
https://www.sqlite.org/lang_keywords.html

This function exists and aims to check if a sql query contains any protected keywords:
`int sqlite3_keyword_check(const char*,int);`
( as found here: https://www.sqlite.org/c3ref/keyword_check.html )

**Comment by Toshiwoz** [comment]
Nice, thanks.

**Comment by 2shady4u** [comment]
Closing this issue because it is not fixable or implementable in this project's plugin.
Any SQLite query should obey the rules as imposed by SQLite itself... and this is not something I can change and/or fix! 😉
