### ISSUE TITLE
SQLCipher Encryption Implementation

### ISSUE THREAD

**Issue by MrSmite** [2shady4u/godot-sqlite#63]
**Is your feature request related to a problem? Please describe.**

Not a problem however the ability to encrypt game data such as logins, email, etc. would be useful.

**Describe the solution you'd like**

SQLCipher is an open source encryption module for SQLite3 that provides 256 bit AES encryption. The license allows for use in commercial products with proper attribution.

[Licensing Information](https://www.zetetic.net/sqlcipher/license/)

**Describe alternatives you've considered**

N/A

**Additional context**

This feature is available in SQLiteStudio, a GUI database manager. When you create a database, you can choose SQLite3 or SQLCipher which encrypts the entire database.

Here are some links:

[SQLiteStudio Home - https://sqlitestudio.pl/](https://sqlitestudio.pl/)
[SQLCipher Home - zetetic.net](https://www.zetetic.net/sqlcipher/)
[Source Code - github](https://github.com/sqlcipher/sqlcipher.git)
[Source Code for Android - github](https://github.com/sqlcipher/android-database-sqlcipher.git)

**Comment by thearduinoguy** [comment]
Absolutely agree that the ability to encrypt the database is essential. Especially when storing user details, passwords, emails, etc.

**Comment by abcjjy** [comment]
Try my fork https://github.com/abcjjy/godot-sqlcipher/tree/gd-extension

Only iOS and Mac is tested.

**Comment by MrSmite** [comment]
@abcjjy Thanks, I use Windows and plan to build for Android. Do you plan to compile any releases for your branch?

**Comment by abcjjy** [comment]
> @abcjjy Thanks, I use Windows and plan to build for Android. Do you plan to compile any releases for your branch?

You can compile it yourself. That's quite straight forward. Sqlcipher is similar with SQLite except several additional flags.

**Comment by MrSmite** [comment]
> > @abcjjy Thanks, I use Windows and plan to build for Android. Do you plan to compile any releases for your branch?
> 
> You can compile it yourself. That's quite straight forward. Sqlcipher is similar with SQLite except several additional flags.

Thanks

**Comment by 2shady4u** [comment]
Hello everyone,

Due to lack of time I won't be able to implement any encryption in this repository in the near future.
I will add [abcjjy](https://github.com/abcjjy)'s [SQLCipher implementation](https://github.com/abcjjy/godot-sqlcipher/tree/gd-extension) to the README.md as an alternative and/or implementation example for people that require the usage of encryption in their projects.

I am closing any future issues with this explanation.
