### ISSUE TITLE
HTML GDNative build - imported function 'env.fseeko' signature mismatch

### ISSUE THREAD

**Issue by IsaaacD** [2shady4u/godot-sqlite#65]
**Environment:**
 - OS: Windows
 - Godot version: 3.4.2.stable.official
 - _godot-sqlite_ version: 3.0.0

**Issue description:**
When exporting the [demo](https://github.com/2shady4u/godot-sqlite/tree/master/demo) to GDNative build of HTML the error `imported function 'env.fseeko' signature mismatch` shows up

**Steps to reproduce:**
clone repo and build HTML of demo

**Comment by 2shady4u** [comment]
Hey @IsaaacD 

Did you use the "GDNative" export option in your HTML export settings?
The example deployment at https://2shady4u.github.io/godot-sqlite/ still seems functional 🤔 

I'm currently taking a little break from godot-sqlite dev so I might not be as present as several months ago, apologies for that 🙏

**Comment by IsaaacD** [comment]
Hey @2shady4u Thanks for the quick response! I did export as "GDNative" and it was using Godot 3.4.2 and it didn't work.

I've downloaded Godot 3.3.2 and it works in HTML now so something changed from 3.3 -> 3.4
