### ISSUE TITLE
HTML5 Project Run In Browser Throws Errors

### ISSUE THREAD

**Issue by droyd5691** [2shady4u/godot-sqlite#68]
**Environment:**
 - OS: Windows 10
 - Godot version: 3.3.4 stable
 - _godot-sqlite_ version: 3.0

**Issue description:**
When I run the project as a HTML5 it throws errors in the developer tools console (see attached screen shots).

I'm expecting the plugin to work as it does when I run the project as a desktop application.

**Steps to reproduce:**
1. Run the project as HTML5

Note: The included minimal reproduction uses 3.0 however I have also tried it with 3.1 with same errors.

**Minimal reproduction project:**
[SQLite HTML5 Issue.zip](https://github.com/2shady4u/godot-sqlite/files/8025952/SQLite.HTML5.Issue.zip)

**Errors**
![image](https://user-images.githubusercontent.com/92029164/153039470-0437abda-613d-4419-accd-e75f99626639.png)

**Comment by 2shady4u** [comment]
Hey @droyd5691!

You'll have to export using the "GDNative" export type as seen here:
![unknown](https://user-images.githubusercontent.com/42484461/153196963-d89387d7-ca2c-4011-8a6a-db40f375f3d7.png)

When using this export type everything works perfectly 🥳 

more information: https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_web.html

**Comment by droyd5691** [comment]
Thank you so much :-)
