### ISSUE TITLE
Support for godot linux server?

### ISSUE THREAD

**Issue by splash21** [2shady4u/godot-sqlite#7]
I added an entry for 'Server' in the gdnlib file, pointing to the X11.64 lib

Running linux server, all I get is "--> SQL error:" with no error message every time I run a query.
The same code runs fine on headless.  Is godot server supported?

**Comment by 2shady4u** [comment]
@splash21

This addon supports linux, windows and macos (and hopefully android in the future when they finally fix the issues on the godot-cpp bindings branch)

Linux works, but I dont think headless or server variants of the plugin will actually work by just using the linux build as a substitute... since there's no way to compile the godot bindings for the headless variant, I am afraid we'll have to wait untill they implement it.

**Comment by 2shady4u** [comment]
on second read-through, im actually amazed that it works on headless :ok_hand:

**Comment by splash21** [comment]
Wrapper works very nicely with headless (great work) .  The project starts up with no complaints using linux server with a .pck file - querying just doesn't work (bummer!)  I was hoping it was just something that needed a tweak...

**Comment by 2shady4u** [comment]
@splash21 I had a small discussion with some Godot experts, and they told me compiling for Linux Server should be quite easy but requires the recompilation of the bindings with an update api.JSON.
I haven't tested this yet, but the process would be something like this:

1. Download "Godot Server" build from the official website.
2. Generate a custom api.JSON using this build:
`_path-to-godot-server-build_/godot.exe --gdnative-generate-json-api api.json`
3. This will create a custom file api.JSON which you will have to supply when you rebuild the godot-cpp bindings (in the godot-cpp folder):
`scons platform=linux generate_bindings=yes use_custom_api_file=yes custom_api_file=../api.json`
4. and lastly the godot-sqlite source code should be compiled using this new bindings binary (in the godot-sqlite folder):
`scons platform=linux bits=64 target=debug`

So in theory it is possible...

**Comment by splash21** [comment]
Thanks, @2shady4u  - appreciate the response.  I'll give it a try  👍

**Comment by 2shady4u** [comment]
I added the Server and Headless entries in the .gdnlib and tested a Headless and Server Godot build with the linux exported .so.

Seems to work fine except for the fact that the database .db has to be deleted otherwise I get SQL query errors: "Cannot write a read-only database"

Will investigate...

**Comment by sesenta** [comment]
Hi, I had this problem today and the solution is easy

when you export to server you only export the pck, but if you are using this plugin you will need to manually export the database and the file inside the x11 folder called libgdsqlite.so

**even if you marked in export / resources / filter to export: * .so, *. db ; you must do it manually**

**summary:**

**Option 1: (most simple)**

export your project for linux without embed pck

in the folder where you export:
-delete the executable, ensure to keep the pck and the "libgdsqlite.so"
-paste your database
-paste the godot server binary and change its name to the same than pck without extension eg:(game.pck => game)
-done

**option 2:**

export only the .pck

in the folder where you export:
-paste the archive named  "libgdsqlite.so" which is in folder addons/godot-sqlite/bin/x11
-paste your database
-paste the godot server binary and change its name to the same than pck without extension eg:(game.pck => game)
-done

**Comment by 2shady4u** [comment]
@sesenta I would like to test this out myself and add the necessary steps to the `README.md` of this repository.
Do you maybe have a project readily available on which I may test this out?

Thanks for reporting your findings btw!

**Comment by sesenta** [comment]
@2shady4u i'm gonna prepare a project for test :)

**Comment by sesenta** [comment]
i dont know how to upload the project to github, how can i share the project?

**Comment by 2shady4u** [comment]
Normally you should be able to drag and drop a `*.zip` archive of your project here.
Like this:
[icon.zip](https://github.com/2shady4u/godot-sqlite/files/6216182/icon.zip)

**Comment by sesenta** [comment]
i had to delete the plugin to get a zip with less than 10 mb XD. so you need install it in the project
[demoSQlite.zip](https://github.com/2shady4u/godot-sqlite/files/6216466/demoSQlite.zip)

the project exported must look as:
[sqliteServerExported.zip](https://github.com/2shady4u/godot-sqlite/files/6216470/sqliteServerExported.zip)
in this folder you need add the godotServer binary and change its name to demoSQlite (i had to delete the godot Server binary too for size).

**Comment by 2shady4u** [comment]
@sesenta Thank you for testing this!
I've added your "how to set up" explanation to the README.md :)

Closing this issue since exporting for server seems to work correctly!
