### ISSUE TITLE
Unable to open dynamic library in exported project (MacOS)

### ISSUE THREAD

**Issue by Methamane** [2shady4u/godot-sqlite#70]
Environment:

OS: MacOS 12.0.1 (m1 Mac mini )
Godot version: 3.4.2
godot-sqlite version: 3.1
Issue description:
Unable to run exported project due to the following error in the log: Can't open dynamic library

Steps to reproduce:
Unsure exactly how to reproduce or if I misunderstood how to properly export (or if any specific settings are needed when exporting).
I'm using the OS.get_user_data_dir() method for the database directory which works properly when in the editor.

Additional context
When I export with debug mode the app runs but is unable to open the database, and when exporting without debug mode the app doesn't run at all.
Also I'm doing all the exporting through the editor as this is the first app that I'm trying to export, I have no prior experience in doing so.
This is a read and write database.

In the Resources tab I'm exporting all the resources and also added *.db in the export non-resource files/folders (even though it shouldn't matter since the db file should be in the os user data dir)

Here are the errors in the log when I try to run the app:
Godot Engine v3.4.2.stable.official.45eaa2daf - https://godotengine.org
OpenGL ES 3.0 Renderer: Apple M1
OpenGL ES Batching: ON
 
ERROR: Can't open dynamic library: /Users/metha/Documents/Projects/Godot/Moni.app/Contents/MacOS/../Frameworks/libgdsqlite.dylib, error: dlopen(/Users/metha/Documents/Projects/Godot/Moni.app/Contents/MacOS/../Frameworks/libgdsqlite.dylib, 0x0002): tried: '/Users/metha/Documents/Projects/Godot/Moni.app/Contents/MacOS/../Frameworks/libgdsqlite.dylib' (code signature in <BA9D4644-D948-3D0D-9DCD-5D792BD4DA38> '/Users/metha/Documents/Projects/Godot/Moni.app/Contents/Frameworks/libgdsqlite.dylib' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/usr/lib/libgdsqlite.dylib' (no such file), '/Users/metha/Documents/Projects/Godot/Moni.app/Contents/Frameworks/libgdsqlite.dylib' (code signature in <BA9D4644-D948-3D0D-9DCD-5D792BD4DA38> '/Users/metha/Documents/Projects/Godot/Moni.app/Contents/Frameworks/libgdsqlite.dylib' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/usr/lib/libgdsqlite.dylib' (no such file).
   at: open_dynamic_library (platform/osx/os_osx.mm:1917) - Condition "!p_library_handle" is true. Returned: ERR_CANT_OPEN
ERROR: No valid library handle, can't get symbol from GDNative object
   at: get_symbol (modules/gdnative/gdnative.cpp:510) - No valid library handle, can't get symbol from GDNative object
ERROR: No nativescript_init in "res://addons/godot-sqlite/bin/osx/libgdsqlite.dylib" found
   at: init_library (modules/gdnative/nativescript/nativescript.cpp:1510) - No nativescript_init in "res://addons/godot-sqlite/bin/osx/libgdsqlite.dylib" found

**Comment by 2shady4u** [comment]
Hi @Methamane !

Seems like the exported game isn't able to open the dynamic library for some reason 🤔 
Normally you should be able to export the game in the editor without any issue. Godot should automatically copy the the .dylib to the build-folder (Wherever you set it). 

What are you exactly copying to the user/-folder?

Could you also check if the dynamic library is actually present alongside the exported PCK and executable?

**Comment by Methamane** [comment]
Hi @2shady4u,

No it doesn't look like the "res://addons/godot-sqlite/bin/" folder has an "osx" folder or the libgdsqlite.dylib file.
I'm going to build a Windows laptop soon so I'll test if the exporting work well on a different platform, but I'm not sure if this is a Godot bug or me doing something wrong.

I'm not copying anything into the user folder, I'm using the OS.get_user_data_dir() method as a path to create and use the database.

Sorry for the delayed response, hectic times.

**Comment by Methamane** [comment]
Hi @2shady4u,

It works without any issues on Windows, I think that the problem is with the export on Mac.
Mac didn't even export a pck when I exported the project (I exported it separately) so it seems to me like a Godot bug.
Just for clarification when I click on export project on the Mac it just exports the executable and nothing else, on Windows it exported the pck and a dll alongside the executable.

**Comment by 2shady4u** [comment]
I've searched a bit in both the godot and godot-cpp repositories and I've come up with nothing :(

The only issue that might (?) be related is this one:
https://github.com/godotengine/godot-cpp/issues/592

Is it possible to export a project without the Godot-SQLite plugin, such that we can check if the issue goes hand-in-hand with GDNative or if it is just a more general Godot problem?

**Comment by Methamane** [comment]
Hey @2shady4u,

Checking "disable library validation" solved the problem!
Didn't test all the features yet but it's creating the database, and reading/writing data.
Thanks for all the help and patience!
