### ISSUE TITLE
Move the Open and Close DB logging under verbose mode and more

### ISSUE THREAD

**Issue by tokengamedev** [2shady4u/godot-sqlite#73]
**Is your feature request related to a problem? Please describe.**
Move the database open and closed logging under verbose mode

In case of opening a read-only database, there is also a message "READ" is displayed along with the path of the file. 
Can this be changed to added a Symbol **R(EADONLY)**in the opening DB message itself.

Current is:
```
res://data/some_db_name.db
READ
Opened database successfully (res://data/some_db_name.db)
Closed database (res://data/some_db_name.db)
```
Suggestion is:
```
Opened database successfully (res://data/some_db_name.db) R
or 
Opened database successfully (res://data/some_db_name.db) READONLY
```

**Describe the solution you'd like**
Logging of the database open and closed should happen when the DB Verbose mode is on 

**Describe alternatives you've considered**
None, as it is a minor issue and does not impact core functionality

**Additional context**
This logging is valuable when you are creating or modifying the database itself, but when you move into implementing game logic and other stuff, it comes in the way as it is pretty long statement and messages are lost if there are few connections.

Also the output window can handle a limited amount of messages only.

**Comment by 2shady4u** [comment]
Hi @tokengamedev,

I agree that the verbosity should be extended with a QUIET mode which stops all console output (except for errors).

In the case of a read-only database the "READ" output that is displayed is a remnant that I did not clean up... :(
Would it be useful if this became an actual feature?

Also, you can change the verbose_mode on the fly = only enable it when you want it

**Comment by tokengamedev** [comment]
> I agree that the verbosity should be extended with a QUIET mode which stops all console output (except for errors).
>
It would be great to have this as a feature 

> In the case of a read-only database the "READ" output that is displayed is a remnant that I did not clean up... :( Would it be useful if this became an actual feature?

I understand, but as I looked into the code, and wondered, why other modes were not printing. Anyway, it would make sense to have a small feature as there are scenarios where we have both (Readonly and ReadWrite databases) in the same application/game.

> Also, you can change the verbose_mode on the fly = only enable it when you want it

Agreed

**Comment by 2shady4u** [comment]
I've added a brand-new `verbosity_level`-variable that allows much finer control of this plugin's console logging in the latest release (https://github.com/2shady4u/godot-sqlite/releases/tag/v3.2).

I'm closing this issue as a result of this this release. 🙏

**Comment by tokengamedev** [comment]
Thanks a lot @2shady4u. I will check out the changes sometime soon.  Also thanks for updating the sqlite db code too, although not mentioned in the release notes.  appreciate the hard work.
