### ISSUE TITLE
What happened to fetch_array?

### ISSUE THREAD

**Issue by gyrcom** [2shady4u/godot-sqlite#74]
I am updating my code to new versions of godot and gdsqlite and it broke looking for fetch_array.... is this a feature??

**Comment by 2shady4u** [comment]
Hi @gyrcom 

I'm not really sure what you mean by "fetch_array"? I've never implemented any method with that name in this project.

Are you perhaps confusing my version of `godot-sqlite` with Khairul's old gdsqlite plugin? While both projects have the same goal (making SQLite accessible in Godot), they are totally independent from each other and use different methods and variables.

**Comment by gyrcom** [comment]
AH thats got to be it, Similar things with the same name....

**Comment by 2shady4u** [comment]
I'm closing this issue as it is not relevant to this repository...
