### ISSUE TITLE
Any plans (or advice) to create a Raspberry Pi compatible binary?

### ISSUE THREAD

**Issue by jgodfrey** [2shady4u/godot-sqlite#75]
**Is your feature request related to a problem? Please describe.**
Not a problem, but I'm seeking a Raspberry Pi compatible binary.

**Describe the solution you'd like**
I'd like to use this project on a Raspberry Pi (alongside the unofficial Raspberry Pi Godot build - https://github.com/hiulit/Unofficial-Godot-Engine-Raspberry-Pi)

**Describe alternatives you've considered**
There isn't another SQLite alternative that I'm aware of.

**Additional context**
I'm creating a Godot-based digital picture frame application that's powered by a Raspberry Pi. I've previously created such an application based on Python and pi3d, but having the power of the Godot game engine behind the app offers lots of advantages. So, I'm in the process of tracking down all of the pieces I'd need to replace the original app with a Godot version. SQLite is the only major missing piece ATM. 

I've tried to install the linux/X11 library from this project on the Pi, but running a sample project results in:

ERROR:  does not have a library for the current platform.
   at: init_library (modules/gdnative/nativescript/nativescript.cpp:1486)

I assume that's because the linux binaries are probably not built for ARM-based hardware (?).

**Comment by 2shady4u** [comment]
Hello @jgodfrey,

Disclaimer: I don't have any experience with using Raspberry PI

On the other hand I don't see why it shouldn't be possible if the correct compiler flags are adopted.
These flags seem to be documented in the Raspberry PI repository that you linked.
I would recommend just trying it actually and seeing what happens.

As this is an issue that is more related to `godot-cpp` itself (as this library depends on it) I do think it would be more useful to open an issue in [that](https://github.com/godotengine/godot-cpp) repository to ask if it is actually possible to achieve this.

Another alternative would be for you to use the [Godot-SQLite module]() instead. This would require that you compile Godot from scratch using the proper compiler flags (again: as documented in that repository you linked).

Too bad the linux binaries don't work out of the box :'(

**Comment by jgodfrey** [comment]
Thanks for the fast and informative response @2shady4u - much appreciated. I'll poke around a bit based on your advice and see if I can make any progress. I'll report back if I have any news.

**Comment by 2shady4u** [comment]
I am closing this one due to inactivity! 😃
