### ISSUE TITLE
Schema version capability

### ISSUE THREAD

**Issue by bitbrain** [2shady4u/godot-sqlite#79]
Maybe something that can be solved outside of this plugin, however, I was curious if anybody already solved the issue of creating database schema versioning. 

Let us say that I want to create some tables but once these tables are created, I do not want to create them any longer. Much later I want to add another table that should get created once. In Java, there are libraries such as [liquibase](https://www.liquibase.org/) that do that for you, by hashing and tracking database schema changes within a database table itself.

**Comment by 2shady4u** [comment]
Hi @bitbrain 

There seems two relevant options in SQLite that enable you to set the version of your database using following pragma-commands:
https://www.sqlite.org/pragma.html#pragma_user_version
https://www.sqlite.org/pragma.html#pragma_schema_version

Ofc. you would have to implement the necessary logic yourself, either in your SQL-statement or in GDScript.

In your opinion: How would this plugin go about alleviating the implementation of some kind of schema version capability? In a general sense such that it is re-usable in the cases where this would be useful.

**Comment by bitbrain** [comment]
> In your opinion: How would this plugin go about alleviating the implementation of some kind of schema version capability? In a general sense such that it is re-usable in the cases where this would be useful.

[This thread contains some good examples](https://stackoverflow.com/a/1058553) on how to facilitate the user version for this purpose.

One way I could see this working is a "migration" directory (e.g. `res://sqlite`) in which files are stored in the format `<number`__anynamehere.sql` that contain these migrations. Then, this plugin scans all SQL files and applies the versions it needs to apply to and then sets a new user version to the latest.

When I then want to introduce a new migration (e.g. new patch or game update) I simply add a new .sql file with a version on it, and when the game starts up for the player, it will then apply that new migration (but skip the existing ones)

**Comment by 2shady4u** [comment]
I'm still confused if, according to you, this is something that has to be implemented on the C++ or the GDscript side?

**Comment by 2shady4u** [comment]
@bitbrain please tell me if you make such a thing :D I would love to see it
