### ISSUE TITLE
Trouble with the print statements, and lack of error codes.

### ISSUE THREAD

**Issue by avencherus** [2shady4u/godot-sqlite#8]
Thanks for the work on this.  I have been having some issues with using it.

For example in a tool/debug build doing a loop for 50,000 inserts (lots of log data in my case), I get 100,000 print statements.

> INSERT INTO ..
> --> Query succeeded
> INSERT INTO ..
> --> Query succeeded
> INSERT INTO ..
> --> Query succeeded
...

Is another approach intended here?  Some of these prints seem unnecessarily verbose.  Returning error codes instead of true/false would be more flexible for the end user.

It would be nicer to have control over how the failures are managed, and if a print statement is desirable versus quietly logging something.

**Comment by 2shady4u** [comment]
Hello!

Is your 'verbose_mode'-variable disabled? When setting 'verbose_mode' to false, these prints should not appear anymore. Only failures/errors/crashes will get displayed in that case.

**Comment by avencherus** [comment]
Thanks, yes that does help.  I see now, I had copied the boiler plate pieces from the demo and missed that line.
