### ISSUE TITLE
Add get_query_result(duplicate := true) method or other solution to not duplicate query_result

### ISSUE THREAD

**Issue by Koyper** [2shady4u/godot-sqlite#81]
**Is your feature request related to a problem? Please describe.**
The new modification that duplicates query_result will reduce performance for certain queries that return a lot of data. On a table with about 1000 rows with some binary data, there is about a 10-15% increase in query time compared to the last version without the duplicate (a non-rigorous test).

**Describe the solution you'd like**
Provide a way to get the query_result without duplicating it first.

**Describe alternatives you've considered**
Because the query_result property goes through the setter, I don't think you can bypass the duplicate?

**Comment by Koyper** [comment]
Hi @2shady4u 

While using something like the `auto_duplicate_result` parameter would work, the GDScript becomes a bit clumsy because you would typically bookend the query_result call with setting the parameter to false, then back to true.

One idea would be to have a one-shot parameter like `skip_next_result_duplicate` this:
```
Array SQLite::get_query_result()
{
    if (skip_next_result_duplicate)
    {
        skip_next_result_duplicate = false;
        return query_result;   
    }
    else 
    {
        query_result.duplicate(true);
    }
}
```

The other idea is going back to having a new, separate method like `get_unduplicated_query_result`, which I think I prefer for easier code reasoning.

Thanks!

**Comment by 2shady4u** [comment]
Another proposal (the one I'm currently most happy about) is to add another property that has the `get_unduplicated_query_result` as its setter, as such:

```C++
register_property<SQLite, Array>("query_result", &SQLite::set_query_result, &SQLite::get_query_result, Array())
register_property<SQLite, Array>("raw_query_result", &SQLite::set_query_result, &SQLite::get_unduplicated_query_result, Array())

Array SQLite::get_query_result()
{
    return query_result.duplicate(true);
}

Array SQLite::get_unduplicated_query_result()
{
    return query_result;   
}
```

I don't like the one-shot implementation of the proposed `skip_next_result_duplicate`-property as all user-variables should, preferably, only be modified by the user themselves.

**Comment by Koyper** [comment]
Yes! This is a good solution and solves the issue - much better than the one-shot idea. Nice and tidy.

The only refinement I would consider is a matter of semantics, i.e., naming the new property `unduplicated_query_result` because it implies that `query_result` is duplicated, whereas `raw` gives no hint about what the "unraw" version is doing.  Perhaps `query_result_reference` is more descriptive?

**Comment by 2shady4u** [comment]
Hi @Koyper 

I've implemented the requested change in commit 524e67a5cca2e999a2ef28588a4c697eef6af724
Feel free to give any feedback regarding the committed implementation.

I'm leaving this issue open until v3.3 is released.

**Comment by Koyper** [comment]
Hi @2shady4u 

Thank you so much for this!

I wanted to add that I agree with your decision to make the default behavior as duplicate. When first working with the plugin, that bug of overwriting the prior query while still working with the previous result would be a real hair-puller.

**Comment by 2shady4u** [comment]
This has now been implemented in the latest release! 🙏 

Closing this issue as a result!
