### ISSUE TITLE
Should reads be mutexed?

### ISSUE THREAD

**Issue by andersmmg** [2shady4u/godot-sqlite#82]
I update the database in a thread sometimes, so it's mutexed when I need to write to it. Currently, I don't lock the mutex when I'm just reading data, but should I? I can't seem to find a lot of documentation on this. Thanks!

**Comment by 2shady4u** [comment]
Hello @andersmmg 

According to [this](https://www.sqlite.org/threadsafe.html) article, the SQLite database is thread-safe if the plugin is compiled with either:
```
-DSQLITE_THREADSAFE=1
```
or:
```
-DSQLITE_THREADSAFE=2
```

I don't supply this compiler parameter and thus the default value applies which is 1 (= Serialized, which allows full multi-threading without restrictions) 🥳

**Comment by 2shady4u** [comment]
Closing this issue as it has been resolved.

Feel free to open a new issue if you encounter any new and exotic problems 🙏
