### ISSUE TITLE
Verbosity Levels not working in Linux

### ISSUE THREAD

**Issue by Cryptoclysm** [2shady4u/godot-sqlite#83]
**Environment:**
 - OS: Linux - Debian 11
 - Godot version: 3.4.2 Mono
 - _godot-sqlite_ version: 3.3

**Issue description:**
Database opens and database closes still log, even when `db.verbosity_level=0` (Quiet) is set.

The same code that runs on Windows without logging will still have logging occur on Linux.

```
Opened database successfully (./godot/app_userdata/db/db.db)
Closed database (./godot/app_userdata/db/db.db)
```

**Steps to reproduce:**

```
db1 = SQLite.new()
db1.path = "db.db"
db1.verbosity_level = 0

db1.open_db()
db1.close_db()
```

**Minimal reproduction project:**

(Can create this if desired at a later date)

**Additional context**

Tested using the 'Server' binary of Godot. I believe that the same will happen using a standard binary to run the project.

**Comment by 2shady4u** [comment]
Hi @Cryptoclysm,

I can't seem to replicate this bug :/
I'm running the supplied code on Ubuntu 20.04 with Godot 3.4.4 and get the expected result.
I currently don't really have the capability to easily test a mono build of Godot with the supplied code.

Some questions:
- Would it be possible to run the same code (as given in your steps) on a non-mono version of the engine?
- If you are using mono, you should also be able to use the SQLite library that is supplied by C# itself if I'm not mistaken. This might a better fit for your project if you are aiming to stick with godot-mono?

**Comment by Cryptoclysm** [comment]
Hi @2shady4u  Thanks for looking into this.

I've resolved the issue: When deploying to a Godot server binary, usually only the PCK file is updated, and so I was still running an old version of Godot SQLite without realising it.
Updating the the libgdsqlite.so file to the latest version next to the binary resolved the issue.

Thank you for your great work on this library!
