### ISSUE TITLE
Unable to open database in android 10 [chinese tablet, unisoc sc9863a]

### ISSUE THREAD

**Issue by MyQ-TeK** [2shady4u/godot-sqlite#84]
I have followed your instructions, but for some reason it will create the db on first run but it is empty, and adb logcat shows that it cannot access database, but it has created it. even demo is the same. What Am I missing here ? I can replace the db with a populated one easily enough and can read it with sqlite explorer on pc fine, but android does not show the app dir in the /data/data/ ie the org.godotengine.appname apps home dir can u help me here?

**Comment by 2shady4u** [comment]
Hi @MyQ-TeK!

Some questions:
- Where are you creating your database? (in the user:// or in the res://-folder?)
- When saying "even demo is the same"; do you mean that you tested the demo-project on your tablet and it also failed?
- If yes, what error messages do you get?

I'm gonna need some more information to figure this one out I think 😅

**Comment by MyQ-TeK** [comment]
Thanks for your reply, I have been working with godot for about 6 months, but I am not using it for a game. I am trying to use it to make a UI control for an ubuntu server to control user settings for recording sessions to automate a digital audio studio using a tablet as the terminal. I have learned what I know about godot by resolving each problem one at a time. So I would be a noob with a couple of extras. The idea is to use sqlite with a local database on the tablet for the demo version, and then to swap to the database to the server later.

The problem is it works great on the ubuntu platform, but when I try it in android its does not read the database at all, although ist does create it and gives no errors to the user, the only place i can find some info is with adb debug, which seems to say that the permissions are wrong saying it cannot open it.
the auto created data base ha rw------- permissions. I could be wrong.

I am very used to ubuntu, but have no knowledge of android studio etc, could you indicate to me what info u require so I can put it together and post it.

sorry to be a pain.

**Comment by 2shady4u** [comment]
I require the following information to help you 😄 :
- What is the database-path that you use in your Godot code? (db.path = ???)
- Are you creating your database using read-only permissions or are you using read-write permissions? (What is the value of db.read_only?)

Would also be easy for me if you share the relevant part of project's code.

**Comment by MyQ-TeK** [comment]
OK, ThanX,
1] I use user://SMstudio.db As path not rec://
2] I am not setting db.read_only anywhere, was not aware.
3] I will post relevant code A.S.A.P, not at my work computer at the mo
ThanX

**Comment by 2shady4u** [comment]
Hello @MyQ-TeK,

Is there any update on this issue?

**Comment by 2shady4u** [comment]
Closed #84 due to inactivity
