### ISSUE TITLE
how could i do a query with "where var=string"?

### ISSUE THREAD

**Issue by sesenta** [2shady4u/godot-sqlite#9]
func login(usuario:String,password:String):
>    db.query("SELECT user FROM " + table_name + "WHERE user=" + usuario + ";")

output:
 --> SQL error: near "=": syntax error

cause query needs ", but godot too use it

PD: thanks so much for this asset

**Comment by 2shady4u** [comment]
Hello!

You should be able to use single quotes ' in that case.
which would look as follows:
`db.query("SELECT user FROM '" + table_name + "' WHERE user='" + usuario + "';")`

or if using the format string method:
`db.query("SELECT user FROM '{0}' WHERE user='{1}';".format([table_name, usuario]))`

**Comment by sesenta** [comment]
worth!, thank you
