### ISSUE TITLE
Get Godot Editor to recognize SQLite as a class

### ISSUE THREAD

**Issue by engineer-pearl** [2shady4u/godot-sqlite#94]
**Is your feature request related to a problem? Please describe.**

As I am developing, I often use the built-in help tools such as autocomplete and help text to make sure I am calling the right functions. For this plugin, Godot does not recognize the class, which means I am more likely to mistype functions and need to keep the github documentation up in order to read it.

**Describe the solution you'd like**

I am not familiar with how this plugin was built, so the best I can think of is enclosing the SQLIte component in a wrapper class designed primarily to provide documentation. The user would then load the wrapper class, and gain access to autocomplete functionality and in-ide documentation.

**Describe alternatives you've considered**

I am currently leaving the GitHub page up  while I am developing so I can reference its documentation.

**Additional context**

OS: Linux Mint (X11)
Godot Version: v3.5.1.stable.official
![image](https://user-images.githubusercontent.com/17389425/195001358-fbd7d9aa-6f21-4166-bb10-d4b1b4a3b218.png)

**Comment by 2shady4u** [comment]
Hi @engineer-pearl!

I've wanted to implement this for a long time, but there currently isn't any support for implementing this in a straight-forward manner in GDNative (Godot 3.X). Fortunately this is now being natively supported by GDExtension (Godot 4.X).

Thus to summarize:

## Current version of the plugin (GDNative, Godot 3.5.1)
Documentation is not natively supported so the only way to implement this would be to use a wrapper (like you proposed).
Unfortunately, I currently don't have time to implement this and would rather spend the time that I have available to work on bugs, crashes and preparing the upcoming Godot 4.0 version of this plugin.

## Future/upcoming version of the plugin (GDExtension, Godot 4.0):
Documentation is **natively supported** by GDExtension so I'll be able to make the relevant parts of this repo's `README.md` easily available in the Godot editor.

I'm sorry for not having the necessary resources available at the current moment. 🙏 
Also, you are always free to create a pull request. 😄

**Comment by 2shady4u** [comment]
> I'm not going to be able to work on the 4.0 extension just yet, but I can probably justify working on the wrapper class. Have you already begun the documentation for the 4.0 version? If so, where would I find it? I would like to make sure my documented version is consistent with yours.

I haven't started on the documentation of the Godot 4.0 as I've been mostly busy making the new plugin feature complete.
Also there might be some non-backwards compatibility stuff that I'll introduce (if there's time) to make the plugin a bit more stream-lined.

Currently most of the current documentation (as found in the `README.md`) is still relevant even for the GDExtension version of this plugin.

**Comment by engineer-pearl** [comment]
Okay. I will build the documentation primarily off of that then.

**Comment by engineer-pearl** [comment]
I have created pull request #97 to add the desired features.

For the GitHub algorithm:

Fixed #97
